// Package dnsactivity is the narrow contract between routerd and
// router-applyd for opt-in DNS lookup statistics.
//
// It deliberately lives outside internal/apply, internal/config and
// internal/services: those packages are compiled into the bootstrap tools
// (router-update, router-recovery, router-setup), which must stay
// byte-identical between releases for A/B web updates to be accepted. The
// feature therefore keeps its setting in routerd's own store and talks to the
// helper over a dedicated socket instead of the canonical apply transaction.
package dnsactivity

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"time"
)

const (
	// SocketPath is the helper's DNS activity socket, next to apply.sock.
	SocketPath = "/run/minimalrouter/dns-activity.sock"
	// QueryLogPath is on tmpfs, so query lines never reach the disk. dnsmasq
	// opens it as root before dropping privileges, so no directory has to
	// exist before dnsmasq starts.
	QueryLogPath = "/run/minimalrouter-dns-queries.log"
	// DropInPath is read by dnsmasq through the distribution's
	// conf-dir=/etc/dnsmasq.d/,*.conf, alongside the generated
	// minimalrouter.conf, which this feature never modifies.
	DropInPath = "/etc/dnsmasq.d/minimalrouter-dns-activity.conf"

	ProtocolVersion  = 1
	MaxRequestBytes  = 4 << 10
	MaxResponseBytes = 256 << 10
)

// DropIn is the only content the helper ever writes to DropInPath.
// Asynchronous logging drops lines instead of delaying answers if the log
// ever falls behind.
func DropIn() string { return DropInFor(QueryLogPath) }

// DropInFor renders the drop-in for a query log path; tests use a temporary one.
func DropInFor(logPath string) string {
	return "# Generated by Minimal Router OS — DNS activity statistics\n" +
		"# Queries are logged to tmpfs and drained by router-applyd every minute.\n" +
		"log-queries\n" +
		"log-facility=" + logPath + "\n" +
		"log-async=50\n"
}

// Request asks the helper to converge query logging on Enabled and, when
// enabled, to return one page of collected lookups.
type Request struct {
	Version int  `json:"version"`
	Enabled bool `json:"enabled"`
}

// Lookup is how often one client looked up one name since the previous
// drain. LastSeen is the Unix time the lookup was collected from the log, at
// most a minute after it happened.
type Lookup struct {
	Client   string `json:"client"`
	Name     string `json:"name"`
	Count    uint32 `json:"count"`
	LastSeen int64  `json:"last_seen"`
}

// Response is one page of drained lookups. Dropped counts lookups that were
// parsed but not itemized because a memory bound was reached; More asks the
// caller to drain again before the next collection round.
type Response struct {
	Success bool     `json:"success"`
	Error   string   `json:"error,omitempty"`
	Enabled bool     `json:"enabled"`
	Entries []Lookup `json:"entries"`
	Dropped uint64   `json:"dropped"`
	More    bool     `json:"more"`
}

// Client talks to the helper's DNS activity socket.
type Client struct {
	SocketPath string
}

func NewClient() *Client { return &Client{SocketPath: SocketPath} }

func (c *Client) Drain(ctx context.Context, enabled bool) (Response, error) {
	dialer := net.Dialer{Timeout: 5 * time.Second}
	conn, err := dialer.DialContext(ctx, "unix", c.SocketPath)
	if err != nil {
		return Response{}, fmt.Errorf("connect to router-applyd DNS activity socket: %w", err)
	}
	defer conn.Close()
	deadline := time.Now().Add(30 * time.Second)
	if ctxDeadline, ok := ctx.Deadline(); ok && ctxDeadline.Before(deadline) {
		deadline = ctxDeadline
	}
	if err := conn.SetDeadline(deadline); err != nil {
		return Response{}, err
	}
	if err := json.NewEncoder(conn).Encode(Request{Version: ProtocolVersion, Enabled: enabled}); err != nil {
		return Response{}, fmt.Errorf("send DNS activity request: %w", err)
	}
	if unixConn, ok := conn.(*net.UnixConn); ok {
		if err := unixConn.CloseWrite(); err != nil {
			return Response{}, err
		}
	}
	return DecodeResponse(conn)
}

// DecodeResponse reads exactly one bounded response object.
func DecodeResponse(reader io.Reader) (Response, error) {
	var response Response
	data, err := io.ReadAll(io.LimitReader(reader, MaxResponseBytes+1))
	if err != nil {
		return response, fmt.Errorf("read DNS activity response: %w", err)
	}
	if len(data) > MaxResponseBytes {
		return response, errors.New("DNS activity response exceeds limit")
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&response); err != nil {
		return response, fmt.Errorf("decode DNS activity response: %w", err)
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		return response, errors.New("DNS activity response has trailing data")
	}
	if !response.Success {
		if response.Error == "" {
			response.Error = "DNS activity request failed"
		}
		return response, errors.New(response.Error)
	}
	return response, nil
}

// DecodeRequest reads exactly one bounded request object.
func DecodeRequest(reader io.Reader) (Request, error) {
	var request Request
	data, err := io.ReadAll(io.LimitReader(reader, MaxRequestBytes+1))
	if err != nil || len(data) > MaxRequestBytes {
		return request, errors.New("invalid or oversized DNS activity request")
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&request); err != nil {
		return request, errors.New("invalid DNS activity request")
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		return request, errors.New("DNS activity request must contain exactly one object")
	}
	if request.Version != ProtocolVersion {
		return request, errors.New("unsupported DNS activity protocol version")
	}
	return request, nil
}
