#!/bin/sh
# MinimalRouter torture lab — deploy/provision orchestrator.
# Run from the mac; operates on the Proxmox host via SSH + qm guest exec.
# Idempotent. Steps: isp | sim | client | mr | configure | all
#
#   isp     provision ISP-LAB: pppoe-server, dnsmasq, NAT, lab-fault tool
#   sim     provision SIM-LAB: wg0/wg1 peers, HTTP/HTTPS/NTP, extra-LAN service
#   client  provision LAN-CLIENT: check tooling
#   mr      MR-TEST: pristine wipe + install current dist with fault hooks
#   configure  MR-TEST full lab profile via API (needs isp+sim done)
#   keys    report current lab WireGuard keys

set -eu

HOST="${LAB_HOST:-root@192.168.1.2}"
SSHOPTS="-o BatchMode=yes -o ConnectTimeout=10"
KEY="${LAB_SSH_KEY:-$(dirname "$0")/../../private/secrets/proxmox_codex_ed25519}"
KNOWN_HOSTS="${LAB_KNOWN_HOSTS:-$(dirname "$0")/../../private/secrets/proxmox_known_hosts}"
LABDIR="$(cd "$(dirname "$0")" && pwd)"
SEC="$(cd "$LABDIR/../../private/secrets" && pwd)"
PKEY="$(cat "$SEC/lab_id_ed25519.pub")"
H() { ssh $SSHOPTS -i "$KEY" -o UserKnownHostsFile="$KNOWN_HOSTS" "$HOST" "$@"; }

# gx <vmid> <sh command> — guest exec with decoded stdout
gx() {
  H "qm guest exec $1 -- sh -c \"$2\"" | python3 -c '
import json,sys,base64
try:
    d=json.load(sys.stdin).get("out-data","")
    sys.stdout.write(base64.b64decode(d).decode("utf-8","replace"))
except Exception as e:
    sys.stderr.write("gx decode: %s\n" % e)'
}

# putfile <vmid> <local> <guest-path> [mode] — base64 chunk push (runbook pattern)
putfile() {
  vmid="$1"; localf="$2"; guestp="$3"; mode="${4:-600}"
  scp -q $SSHOPTS -i "$KEY" -o UserKnownHostsFile="$KNOWN_HOSTS" "$localf" "$HOST:/tmp/pf_"
  H "base64 -w0 /tmp/pf_ > /tmp/pf.b64 && split -b 500000 /tmp/pf.b64 /tmp/pfc_
qm guest exec $vmid -- sh -c 'rm -f /tmp/pf.b64' >/dev/null 2>&1
for cf in /tmp/pfc_*; do qm guest exec $vmid --pass-stdin 1 -- sh -c 'cat >> /tmp/pf.b64' < \"\$cf\" >/dev/null 2>&1; done
qm guest exec $vmid -- sh -c 'base64 -d /tmp/pf.b64 > \"$guestp\" && chmod $mode \"$guestp\" && ls -la \"$guestp\"' 2>&1 | tail -1
rm -f /tmp/pf_ /tmp/pf.b64 /tmp/pfc_*"
}

# runpayload <vmid> <local script> [args] — push + exec payload
runpayload() {
  vmid="$1"; payload="$2"; shift 2
  putfile "$vmid" "$payload" /tmp/payload.sh 755 >/dev/null
  gx "$vmid" "sh /tmp/payload.sh $* 2>&1"
}

wait_boot() {
  vmid="$1"; tries="${2:-60}"
  i=0
  while [ $i -lt "$tries" ]; do
    up="$(gx "$vmid" 'cat /proc/uptime 2>/dev/null | cut -d. -f1' 2>/dev/null | tr -d '\n')"
    if [ -n "$up" ] && [ "$up" -ge 120 ] 2>/dev/null; then
      echo "  VM $vmid settled (uptime ${up}s)"
      return 0
    fi
    sleep 10; i=$((i+1))
  done
  echo "  ERROR: VM $vmid did not settle"; return 1
}

echo "== cloud-init userdata snippets =="
H 'mkdir -p /var/lib/vz/snippets
cat > /var/lib/vz/snippets/lab-userdata.yaml <<EOF
#cloud-config
runcmd:
  - [ sh, -c, "export DEBIAN_FRONTEND=noninteractive; apt-get update -qq && apt-get install -y -qq qemu-guest-agent >/dev/null 2>&1 || true" ]
  - [ sh, -c, "echo '\''labadmin ALL=(ALL) NOPASSWD:ALL'\'' > /etc/sudoers.d/labadmin && chmod 440 /etc/sudoers.d/labadmin && systemctl enable --now qemu-guest-agent || true" ]
power_state:
  mode: reboot
  condition: true
  timeout: 30
EOF
for v in 150 152 153; do qm set $v --cicustom user=local:snippets/lab-userdata.yaml 2>/dev/null || true; done
echo snippets ready'

echo "== ISP-LAB static upstream 192.168.1.240/24 (outside prod DHCP pool 218-237) =="
H 'qm set 150 --ipconfig0 ip=192.168.1.240/24,gw=192.168.1.1 2>&1 | tail -1' || true

echo "== start lab VMs =="
H 'qm start 150 2>&1 | tail -1; qm start 152 2>&1 | tail -1; qm start 153 2>&1 | tail -1; qm start 151 2>&1 | tail -1'

step="${1:-all}"
if [ "$step" = all ] || [ "$step" = isp ]; then
  echo "== provisioning ISP-LAB (150) =="
  wait_boot 150 || exit 1
  runpayload 150 "$LABDIR/payloads/isp-provision.sh" "$PKEY" || exit 1
fi
if [ "$step" = all ] || [ "$step" = client ]; then
  echo "== provisioning LAN-CLIENT (152) =="
  wait_boot 152 || exit 1
  runpayload 152 "$LABDIR/payloads/client-provision.sh" || exit 1
fi
if [ "$step" = all ] || [ "$step" = sim ]; then
  echo "== provisioning SIM-LAB (153) =="
  wait_boot 153 || exit 1
  runpayload 153 "$LABDIR/payloads/sim-provision.sh" || exit 1
fi
if [ "$step" = all ] || [ "$step" = mr ]; then
  echo "== MR-TEST (151): pristine wipe + install current dist =="
  wait_boot 151 90 || exit 1
  putfile 151 "$LABDIR/payloads/mr-install.sh" /tmp/mr-install.sh 755 >/dev/null
  putfile 151 "$LABDIR/../../build/minimalrouter-linux-amd64.tar.gz" /tmp/mr-dist.tar.gz >/dev/null
  gx 151 "sh /tmp/mr-install.sh /tmp/mr-dist.tar.gz 2>&1" || exit 1
fi
if [ "$step" = all ] || [ "$step" = configure ] || [ "$step" = keys ]; then
  echo "== WireGuard key exchange =="
  # MR keys were generated by mr-install; SIM keys by sim-provision. Pull all.
  for vm in 151 153; do
    gx "$vm" 'cat /root/lab-wg-keys/*.pub 2>/dev/null; echo; cat /root/lab-wg-keys/*.key 2>/dev/null' > "/tmp/labkeys-$vm.txt" 2>/dev/null || true
  done
  echo "  MR keys:  $(wc -l < /tmp/labkeys-151.txt 2>/dev/null || echo 0) lines"
  echo "  SIM keys: $(wc -l < /tmp/labkeys-153.txt 2>/dev/null || echo 0) lines"
fi
if [ "$step" = all ] || [ "$step" = configure ]; then
  echo "== configuring MR-TEST full lab profile =="
  sh "$LABDIR/lab-mr-configure.sh" || exit 1
fi

echo "== deploy done =="
