//go:build linux

package telemetry

import (
	"bufio"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/vladimirperovic/minimalrouter/internal/storage"
	"golang.org/x/sys/unix"
)

type cpuTicks struct {
	total uint64
	idle  uint64
}

var (
	cpuSampleMu   sync.Mutex
	lastCPUSample cpuTicks
	lastCPUAt     time.Time
	lastCPUPct    float64
)

func readUint(path string) uint64 {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	value, _ := strconv.ParseUint(strings.TrimSpace(string(data)), 10, 64)
	return value
}

// readCPULoadPercent returns real CPU utilization since the previous call,
// computed as the busy-jiffies delta from /proc/stat (matching what Proxmox
// reports), falling back to 0 on the first sample.
func readCPULoadPercent() float64 {
	cpuSampleMu.Lock()
	defer cpuSampleMu.Unlock()
	if lastCPUSample.total != 0 && time.Since(lastCPUAt) < 200*time.Millisecond {
		return lastCPUPct
	}
	data, err := os.ReadFile("/proc/stat")
	if err != nil {
		return 0
	}
	line := strings.Fields(strings.SplitN(string(data), "\n", 2)[0])
	if len(line) < 5 || line[0] != "cpu" {
		return 0
	}
	var total, idle uint64
	for i, field := range line[1:] {
		value, _ := strconv.ParseUint(field, 10, 64)
		total += value
		if i == 3 || i == 4 { // idle + iowait
			idle += value
		}
	}
	if lastCPUSample.total == 0 || total < lastCPUSample.total {
		lastCPUSample = cpuTicks{total: total, idle: idle}
		lastCPUAt = time.Now()
		return 0
	}
	dTotal := total - lastCPUSample.total
	dIdle := idle - lastCPUSample.idle
	lastCPUSample = cpuTicks{total: total, idle: idle}
	lastCPUAt = time.Now()
	if dTotal == 0 {
		return 0
	}
	pct := float64(dTotal-dIdle) / float64(dTotal) * 100
	if pct > 100 {
		pct = 100
	}
	lastCPUPct = pct
	return pct
}

func RuntimeSnapshot(wanInterface, lanInterface, dataDir string) RuntimeStatus {
	status := RuntimeStatus{
		Available:    true,
		OS:           runtime.GOOS,
		Architecture: runtime.GOARCH,
		CPUCount:     runtime.NumCPU(),
	}
	var timex unix.Timex
	clockState, clockErr := unix.Adjtimex(&timex)
	status.TimeSynchronized = clockErr == nil && clockState != unix.TIME_ERROR
	if data, err := os.ReadFile("/proc/uptime"); err == nil {
		fields := strings.Fields(string(data))
		if len(fields) > 0 {
			uptime, _ := strconv.ParseFloat(fields[0], 64)
			status.UptimeSeconds = int64(uptime)
		}
	}
	if data, err := os.ReadFile("/proc/loadavg"); err == nil {
		fields := strings.Fields(string(data))
		for i := 0; i < len(fields) && i < 3; i++ {
			value, parseErr := strconv.ParseFloat(fields[i], 64)
			if parseErr == nil {
				status.LoadAverage = append(status.LoadAverage, value)
			}
		}
	}
	status.CPULoadPercent = readCPULoadPercent()
	if file, err := os.Open("/proc/meminfo"); err == nil {
		scanner := bufio.NewScanner(file)
		var totalKB, availableKB uint64
		for scanner.Scan() {
			fields := strings.Fields(scanner.Text())
			if len(fields) < 2 {
				continue
			}
			value, _ := strconv.ParseUint(fields[1], 10, 64)
			switch strings.TrimSuffix(fields[0], ":") {
			case "MemTotal":
				totalKB = value
			case "MemAvailable":
				availableKB = value
			}
		}
		_ = file.Close()
		status.MemoryTotalBytes = totalKB * 1024
		if totalKB >= availableKB {
			status.MemoryUsedBytes = (totalKB - availableKB) * 1024
		}
	}
	status.Storage = storage.Inspect(dataDir)
	status.DiskTotalBytes = status.Storage.TotalBytes
	status.DiskUsedBytes = status.Storage.UsedBytes
	pppName := "ppp0"
	iface, err := net.InterfaceByName(pppName)
	if err == nil && iface.Flags&net.FlagUp != 0 {
		addresses, _ := iface.Addrs()
		for _, address := range addresses {
			ip, _, parseErr := net.ParseCIDR(address.String())
			if parseErr == nil && ip.To4() != nil {
				status.WANConnected = true
				status.PublicIP = ip.String()
				break
			}
		}
	}
	statsInterface := pppName
	if !status.WANConnected {
		statsInterface = wanInterface
	}
	status.WANMAC = interfaceMAC(wanInterface)
	status.LANMAC = interfaceMAC(lanInterface)
	status.RXBytes = readUint("/sys/class/net/" + statsInterface + "/statistics/rx_bytes")
	status.TXBytes = readUint("/sys/class/net/" + statsInterface + "/statistics/tx_bytes")
	status.ConntrackCount = readUint("/proc/sys/net/netfilter/nf_conntrack_count")
	status.ConntrackMax = readUint("/proc/sys/net/netfilter/nf_conntrack_max")
	if status.ConntrackMax > 0 {
		status.ConntrackUsagePercent = float64(status.ConntrackCount) / float64(status.ConntrackMax) * 100
		if status.ConntrackUsagePercent > 100 {
			status.ConntrackUsagePercent = 100
		}
	}
	// DHCP clients retain leases across a router restart, so telemetry reads the
	// persistent lease database generated by the appliance instead of the old
	// volatile /run location.
	status.DHCPLeases = readDHCPLeases("/var/lib/minimalrouter/dnsmasq.leases")
	status.WireguardPeers = readWireGuardPeers()
	status.WireguardActivePeers = countActive(status.WireguardPeers)
	status.WireGuardClient = readWireGuardClientStatus()
	status.DDNS = inspectDDNS()
	return status
}

func interfaceMAC(name string) string {
	iface, err := net.InterfaceByName(name)
	if err != nil || iface.HardwareAddr == nil {
		return ""
	}
	return iface.HardwareAddr.String()
}

func inspectDDNS() DDNSStatus {
	st := DDNSStatus{}
	if _, err := os.Stat("/run/supervise-inadyn.pid"); err == nil {
		st.Running = true
	}
	entries, err := os.ReadDir("/var/cache/inadyn")
	if err != nil {
		return st
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".cache") {
			continue
		}
		cachePath := filepath.Join("/var/cache/inadyn", entry.Name())
		data, readErr := os.ReadFile(cachePath)
		if readErr != nil {
			continue
		}
		for _, field := range strings.Fields(string(data)) {
			if ip := net.ParseIP(field); ip != nil {
				st.LastIP = field
				continue
			}
			if epoch, parseErr := strconv.ParseInt(field, 10, 64); parseErr == nil && epoch > 1_000_000_000 {
				st.LastUpdate = epoch
			}
		}
		if st.LastUpdate == 0 {
			if info, statErr := os.Stat(cachePath); statErr == nil {
				st.LastUpdate = info.ModTime().Unix()
			}
		}
		break
	}
	st.Hostname = inadynHostname()
	return st
}

func inadynHostname() string {
	data, err := os.ReadFile("/etc/inadyn/inadyn.conf")
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "hostname = ") {
			return strings.Trim(line[len("hostname = "):], `"`)
		}
	}
	return ""
}

// safeWGShow executes only one of the installer-authorized, non-secret
// WireGuard status projections. Unlike `wg show ... dump`, none of these
// commands returns an interface private key or peer preshared key. The doas
// policy matches the complete command+argument vector, so routerd cannot turn
// this telemetry path into general CAP_NET_ADMIN/root command execution.
func safeWGShow(interfaceName, field string) (string, error) {
	if interfaceName != "wg0" && interfaceName != "wg1" {
		return "", os.ErrPermission
	}
	switch field {
	case "endpoints", "allowed-ips", "latest-handshakes", "transfer":
	default:
		return "", os.ErrPermission
	}
	cmd := exec.Command("doas", "/usr/bin/wg", "show", interfaceName, field)
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return string(out), nil
}

func ensureWGPeer(peers map[string]*WireGuardPeerStatus, order *[]string, publicKey string) *WireGuardPeerStatus {
	if peer, ok := peers[publicKey]; ok {
		return peer
	}
	peer := &WireGuardPeerStatus{PublicKey: publicKey}
	peers[publicKey] = peer
	*order = append(*order, publicKey)
	return peer
}

// readWireGuardInterface assembles peer status from four explicit wg(8)
// projections. Public keys are peer identities; private/PSK material never
// enters routerd memory.
func readWireGuardInterface(interfaceName string) []WireGuardPeerStatus {
	peers := make(map[string]*WireGuardPeerStatus)
	order := make([]string, 0, 8)

	if out, err := safeWGShow(interfaceName, "allowed-ips"); err == nil {
		for _, line := range strings.Split(out, "\n") {
			fields := strings.Fields(line)
			if len(fields) < 2 {
				continue
			}
			peer := ensureWGPeer(peers, &order, fields[0])
			peer.AllowedIPs = strings.Join(fields[1:], ", ")
		}
	}
	if out, err := safeWGShow(interfaceName, "endpoints"); err == nil {
		for _, line := range strings.Split(out, "\n") {
			fields := strings.Fields(line)
			if len(fields) < 2 {
				continue
			}
			peer := ensureWGPeer(peers, &order, fields[0])
			if fields[1] != "(none)" {
				peer.Endpoint = fields[1]
			}
		}
	}
	if out, err := safeWGShow(interfaceName, "latest-handshakes"); err == nil {
		now := time.Now().Unix()
		for _, line := range strings.Split(out, "\n") {
			fields := strings.Fields(line)
			if len(fields) < 2 {
				continue
			}
			peer := ensureWGPeer(peers, &order, fields[0])
			if ts, parseErr := strconv.ParseInt(fields[1], 10, 64); parseErr == nil && ts > 0 {
				peer.LastHandshake = ts
				peer.Online = now >= ts && now-ts < 180
			}
		}
	}
	if out, err := safeWGShow(interfaceName, "transfer"); err == nil {
		for _, line := range strings.Split(out, "\n") {
			fields := strings.Fields(line)
			if len(fields) < 3 {
				continue
			}
			peer := ensureWGPeer(peers, &order, fields[0])
			peer.RXBytes, _ = strconv.ParseUint(fields[1], 10, 64)
			peer.TXBytes, _ = strconv.ParseUint(fields[2], 10, 64)
		}
	}

	result := make([]WireGuardPeerStatus, 0, len(order))
	for _, publicKey := range order {
		if peer := peers[publicKey]; peer != nil {
			result = append(result, *peer)
		}
	}
	return result
}

func readWireGuardPeers() []WireGuardPeerStatus {
	return readWireGuardInterface("wg0")
}

func readWireGuardClientStatus() *WireGuardClientStatus {
	peers := readWireGuardInterface("wg1")
	if len(peers) == 0 {
		return nil
	}
	peer := peers[0]
	return &WireGuardClientStatus{
		Endpoint:      peer.Endpoint,
		LastHandshake: peer.LastHandshake,
		RXBytes:       peer.RXBytes,
		TXBytes:       peer.TXBytes,
		Online:        peer.Online,
	}
}
