package services

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"regexp"
	"strings"
	"time"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

const defaultBlocklistURL = "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
const maxBlocklistBytes = 50 * 1024 * 1024

var blockDomainPattern = regexp.MustCompile(`(?i)^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$`)

// GenerateAdBlockConf generates /etc/dnsmasq.d/adblock_hosts.conf
// containing blocked domains derived from the hosts-format blocklist.
// Per-device rules use dnsmasq address= directives on the LAN interface.
func GenerateAdBlockConf(cfg *config.SystemConfig, hostsData []byte) (string, error) {
	if !cfg.AdGuard.Enabled {
		return "", nil
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — AdGuard DNS blocklist\n")
	buf.WriteString("# File: /etc/dnsmasq.d/adblock_hosts.conf\n\n")

	domains := ParseHostsFile(hostsData)
	if len(domains) == 0 {
		domains = BuiltinBlocklist()
	}

	// Global block: sinkhole all listed domains to 0.0.0.0
	buf.WriteString("# ── Global DNS Sinkhole Blocklist ──\n")
	for _, d := range domains {
		buf.WriteString(fmt.Sprintf("address=/%s/0.0.0.0\n", d))
	}
	buf.WriteString(fmt.Sprintf("\n# Total blocked domains: %d\n", len(domains)))

	return buf.String(), nil
}

// DownloadBlocklist fetches a hosts-format blocklist from the configured URL.
// The hardened appliance does not call this from its privileged apply path; it
// remains available for a future unprivileged, signed blocklist workflow.
func DownloadBlocklist(url string) ([]byte, error) {
	if url == "" {
		url = defaultBlocklistURL
	}
	parsed, err := neturlParseHTTPS(url)
	if err != nil {
		return nil, err
	}

	client := &http.Client{
		Timeout: 30 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			if len(via) >= 3 {
				return fmt.Errorf("too many redirects")
			}
			if req.URL.Scheme != "https" || !strings.EqualFold(req.URL.Hostname(), parsed.Hostname()) {
				return fmt.Errorf("cross-origin or non-HTTPS redirect rejected")
			}
			return nil
		},
	}
	resp, err := client.Get(parsed.String())
	if err != nil {
		return nil, fmt.Errorf("download blocklist: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("blocklist download failed: HTTP %d", resp.StatusCode)
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, maxBlocklistBytes+1))
	if err != nil {
		return nil, fmt.Errorf("read blocklist: %w", err)
	}
	if len(data) > maxBlocklistBytes {
		return nil, fmt.Errorf("blocklist exceeds %d bytes", maxBlocklistBytes)
	}

	return data, nil
}

func neturlParseHTTPS(raw string) (*url.URL, error) {
	parsed, err := url.Parse(raw)
	if err != nil || parsed.Scheme != "https" || parsed.Host == "" ||
		parsed.User != nil || parsed.Fragment != "" {
		return nil, fmt.Errorf("blocklist URL must be an absolute HTTPS URL without credentials or fragment")
	}
	return parsed, nil
}

// ParseHostsFile extracts unique domain names from a hosts-format file.
// Lines starting with # or 0.0.0.0 / 127.0.0.1 are processed; the second
// field is treated as a domain name.
func ParseHostsFile(data []byte) []string {
	seen := make(map[string]struct{})
	var domains []string

	scanner := bufio.NewScanner(bytes.NewReader(data))
	scanner.Buffer(make([]byte, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}

		ip := fields[0]
		if ip != "0.0.0.0" && ip != "127.0.0.1" && ip != "::1" {
			continue
		}
		domain := strings.ToLower(strings.TrimSuffix(fields[1], "."))

		// Skip localhost entries
		if domain == "localhost" || domain == "localhost.localdomain" {
			continue
		}
		if len(domain) > 253 || !blockDomainPattern.MatchString(domain) {
			continue
		}

		if _, exists := seen[domain]; !exists {
			seen[domain] = struct{}{}
			domains = append(domains, domain)
		}
	}

	return domains
}

// BuiltinBlocklist returns a curated set of known ad/tracking domains
// as a fallback when no external blocklist is available.
func BuiltinBlocklist() []string {
	return []string{
		// Ads
		"pagead2.googlesyndication.com",
		"adservice.google.com",
		"googleads.g.doubleclick.net",
		"tpc.googlesyndication.com",
		"www.googlesyndication.com",
		"partner.googleadservices.com",
		"ad.doubleclick.net",
		"ad.turn.com",
		"ads.facebook.com",
		"analytics.google.com",
		// Tracking
		"track.google.com",
		"stats.g.doubleclick.net",
		"pixel.facebook.com",
		"graph.facebook.com",
		"tr.snapchat.com",
		"ads.tiktok.com",
		"analytics.tiktok.com",
	}
}
