package services

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

const defaultBlocklistURL = "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

// GenerateAdBlockConf generates /etc/dnsmasq.d/adblock_hosts.conf
// containing blocked domains derived from the hosts-format blocklist.
// Per-device rules use dnsmasq address= directives on the LAN interface.
func GenerateAdBlockConf(cfg *config.SystemConfig, hostsData []byte) (string, error) {
	if !cfg.AdGuard.Enabled {
		return "", nil
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — AdGuard DNS blocklist\n")
	buf.WriteString("# File: /etc/dnsmasq.d/adblock_hosts.conf\n\n")

	domains := ParseHostsFile(hostsData)
	if len(domains) == 0 {
		domains = BuiltinBlocklist()
	}

	// Global block: sinkhole all listed domains to 0.0.0.0
	buf.WriteString("# ── Global DNS Sinkhole Blocklist ──\n")
	for _, d := range domains {
		buf.WriteString(fmt.Sprintf("address=/%s/0.0.0.0\n", d))
	}
	buf.WriteString(fmt.Sprintf("\n# Total blocked domains: %d\n", len(domains)))

	// Per-device service blocking
	if len(cfg.AdGuard.FilterDevices) > 0 {
		buf.WriteString("\n# ── Per-Device Content Filtering ──\n")
		for _, device := range cfg.AdGuard.FilterDevices {
			if !device.Enabled || device.IPAddress == "" {
				continue
			}
			for _, svc := range device.BlockedServices {
				svcDomains, ok := ServiceDomains[svc]
				if !ok {
					continue
				}
				for _, d := range svcDomains {
					// address=/domain/ip — dnsmasq resolves this domain ONLY for that IP
					buf.WriteString(fmt.Sprintf("address=/%s/%s\n", d, device.IPAddress))
				}
			}
		}
	}

	return buf.String(), nil
}

// DownloadBlocklist fetches a hosts-format blocklist from the configured URL.
// Falls back to built-in list on network error.
func DownloadBlocklist(url string) ([]byte, error) {
	if url == "" {
		url = defaultBlocklistURL
	}

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, fmt.Errorf("download blocklist: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("blocklist download failed: HTTP %d", resp.StatusCode)
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, 50*1024*1024)) // 50MB limit
	if err != nil {
		return nil, fmt.Errorf("read blocklist: %w", err)
	}

	return data, nil
}

// ParseHostsFile extracts unique domain names from a hosts-format file.
// Lines starting with # or 0.0.0.0 / 127.0.0.1 are processed; the second
// field is treated as a domain name.
func ParseHostsFile(data []byte) []string {
	seen := make(map[string]struct{})
	var domains []string

	scanner := bufio.NewScanner(bytes.NewReader(data))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}

		ip := fields[0]
		domain := fields[1]

		// Skip loopback and sinkhole entries
		if ip == "0.0.0.0" || ip == "127.0.0.1" || ip == "::1" {
			// This is a blocked domain in hosts format — extract it
			domain = fields[1]
		}

		// Skip localhost entries
		if domain == "localhost" || domain == "localhost.localdomain" {
			continue
		}

		if _, exists := seen[domain]; !exists {
			seen[domain] = struct{}{}
			domains = append(domains, domain)
		}
	}

	return domains
}

// BuiltinBlocklist returns a curated set of known ad/tracking domains
// as a fallback when no external blocklist is available.
func BuiltinBlocklist() []string {
	return []string{
		// Ads
		"pagead2.googlesyndication.com",
		"adservice.google.com",
		"googleads.g.doubleclick.net",
		"tpc.googlesyndication.com",
		"wwwgooglesyndicationcom",
		"partner.googleadservices.com",
		"ad.doubleclick.net",
		"ad.turn.com",
		"ads.facebook.com",
		"analytics.google.com",
		// Tracking
		"track.google.com",
		"stats.g.doubleclick.net",
		"pixel.facebook.com",
		"graph.facebook.com",
		"tr.snapchat.com",
		"ads.tiktok.com",
		"analytics.tiktok.com",
		// Malware / phishing
		"malware.customdomain.com",
		"phishing.example.com",
		"cryptominer.example.com",
	}
}
