package services

import (
	"bytes"
	"fmt"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

type CloudflareConfig = config.CloudflareConfig

// GenerateCloudflareDDNS renders the configuration string for Cloudflare DDNS updates.
func GenerateCloudflareDDNS(cf *CloudflareConfig) (string, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString(fmt.Sprintf("zone_id = \"%s\"\n", cf.ZoneID))
	buf.WriteString(fmt.Sprintf("domain = \"%s\"\n", cf.Domain))
	buf.WriteString(fmt.Sprintf("api_token = \"%s\"\n", cf.APIToken))
	return buf.String(), nil
}

// GenerateCloudflareTunnel renders the /etc/cloudflared/config.yml configuration file.
func GenerateCloudflareTunnel(cf *CloudflareConfig, lanCfg config.LANSettings) (string, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString("# File: /etc/cloudflared/config.yml\n\n")
	buf.WriteString(fmt.Sprintf("tunnel: %s\n", cf.Domain))
	buf.WriteString("credentials-file: /etc/cloudflared/cert.json\n\n")
	buf.WriteString("ingress:\n")
	buf.WriteString(fmt.Sprintf("  - hostname: %s\n", cf.Domain))
	buf.WriteString(fmt.Sprintf("    service: https://%s:443\n", lanCfg.IPAddress))
	buf.WriteString("    originRequest:\n")
	buf.WriteString("      noTLSVerify: true\n")
	buf.WriteString("  - service: http_status:444\n")
	return buf.String(), nil
}
