package services

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

func dynamicDNSProvider(cfg *config.SystemConfig) string {
	provider := strings.ToLower(strings.TrimSpace(cfg.Cloudflare.DDNSProvider))
	if provider == "" {
		// Configurations written before provider-aware DDNS were Cloudflare-only.
		return "cloudflare"
	}
	return provider
}

// GenerateDynamicDNS produces provider-specific configuration for Alpine's
// stable inadyn daemon. No generated shell code is executed. No-IP uses its
// native inadyn provider; Cloudflare remains supported for legacy/current users.
func GenerateDynamicDNS(cfg *config.SystemConfig) (string, error) {
	if !cfg.Cloudflare.DDNSEnabled {
		return "# Dynamic DNS disabled or not configured\n", nil
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — Dynamic DNS\n")
	buf.WriteString("period = 300\n")
	// 30-day forced keep-alive matches No-IP's free-hostname update window;
	// updates on IP change happen regardless of this interval.
	buf.WriteString("forced-update = 2592000\n")
	buf.WriteString("allow-ipv6 = false\n")
	buf.WriteString("secure-ssl = true\n\n")

	switch dynamicDNSProvider(cfg) {
	case "noip":
		buf.WriteString("provider no-ip.com:1 {\n")
		buf.WriteString("    username = " + strconv.Quote(cfg.Cloudflare.DDNSUser) + "\n")
		buf.WriteString("    password = " + strconv.Quote(cfg.Cloudflare.APIToken) + "\n")
		buf.WriteString("    hostname = " + strconv.Quote(cfg.Cloudflare.Domain) + "\n")
		buf.WriteString("}\n")
	case "cloudflare":
		buf.WriteString("provider cloudflare.com:1 {\n")
		buf.WriteString("    username = " + strconv.Quote(cfg.Cloudflare.ZoneName) + "\n")
		buf.WriteString("    password = " + strconv.Quote(cfg.Cloudflare.APIToken) + "\n")
		buf.WriteString("    hostname = " + strconv.Quote(cfg.Cloudflare.Domain) + "\n")
		buf.WriteString("    ttl = 300\n")
		buf.WriteString("    proxied = false\n")
		buf.WriteString("}\n")
	default:
		return "", fmt.Errorf("unsupported dynamic DNS provider %q", cfg.Cloudflare.DDNSProvider)
	}

	return buf.String(), nil
}

// GenerateCloudflareDDNS is retained as a source-compatible wrapper for the
// existing apply pipeline. The generated configuration is provider-aware.
func GenerateCloudflareDDNS(cfg *config.SystemConfig) (string, error) {
	return GenerateDynamicDNS(cfg)
}

// GenerateCloudflareTunnel produces a cloudflared tunnel configuration file.
// The actual tunnel token must be obtained from the Cloudflare dashboard.
func GenerateCloudflareTunnel(cfg *config.SystemConfig) (string, error) {
	if !cfg.Cloudflare.TunnelEnabled || cfg.Cloudflare.TunnelToken == "" {
		return "# Cloudflare Tunnel disabled or not configured\n", nil
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — Cloudflare Tunnel (cloudflared)\n")
	buf.WriteString("# File: /etc/cloudflared/config.yml\n\n")

	token := cfg.Cloudflare.TunnelToken

	buf.WriteString("tunnel: minimalrouter\n")
	buf.WriteString("credentials-file: /etc/cloudflared/credentials.json\n\n")
	buf.WriteString("ingress:\n")
	buf.WriteString("  - hostname: " + cfg.Cloudflare.Domain + "\n")
	buf.WriteString("    service: https://localhost:" + fmt.Sprintf("%d", cfg.System.HTTPSPort) + "\n")
	buf.WriteString("    originRequest:\n")
	buf.WriteString("      noTLSVerify: false\n")
	buf.WriteString("  - service: http_status:404\n\n")

	buf.WriteString("# Tunnel token (for systemd service)\n")
	buf.WriteString("# cloudflared service install " + token + "\n")

	return buf.String(), nil
}
