package services

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

func dynamicDNSProvider(cfg *config.SystemConfig) string {
	provider := strings.ToLower(strings.TrimSpace(cfg.Cloudflare.DDNSProvider))
	if provider == "" {
		// Configurations written before provider-aware DDNS were Cloudflare-only.
		return "cloudflare"
	}
	return provider
}

// GenerateDynamicDNS produces provider-specific configuration for Alpine's
// stable inadyn daemon. No generated shell code is executed. No-IP and
// Cloudflare share the same bounded updater: the provider is contacted only
// when the detected public address changes, plus inadyn's forced keep-alive.
func GenerateDynamicDNS(cfg *config.SystemConfig) (string, error) {
	if !cfg.Cloudflare.DDNSEnabled {
		return "# Dynamic DNS disabled or not configured\n", nil
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — Dynamic DNS\n")
	buf.WriteString("period = 300\n")
	// 30-day forced keep-alive matches No-IP's free-hostname update window;
	// updates on IP change happen regardless of this interval.
	buf.WriteString("forced-update = 2592000\n")
	buf.WriteString("allow-ipv6 = false\n")
	buf.WriteString("secure-ssl = true\n\n")

	switch dynamicDNSProvider(cfg) {
	case "noip":
		buf.WriteString("provider no-ip.com:1 {\n")
		buf.WriteString("    username = " + strconv.Quote(cfg.Cloudflare.DDNSUser) + "\n")
		buf.WriteString("    password = " + strconv.Quote(cfg.Cloudflare.APIToken) + "\n")
		buf.WriteString("    hostname = " + strconv.Quote(cfg.Cloudflare.Domain) + "\n")
		buf.WriteString("    checkip-server = api.ipify.org\n")
		buf.WriteString("    checkip-path = /\n")
		buf.WriteString("    checkip-ssl = true\n")
		buf.WriteString("}\n")
	case "cloudflare":
		buf.WriteString("provider cloudflare.com:1 {\n")
		buf.WriteString("    username = " + strconv.Quote(cfg.Cloudflare.ZoneName) + "\n")
		buf.WriteString("    password = " + strconv.Quote(cfg.Cloudflare.APIToken) + "\n")
		buf.WriteString("    hostname = " + strconv.Quote(cfg.Cloudflare.Domain) + "\n")
		buf.WriteString("    checkip-server = api.ipify.org\n")
		buf.WriteString("    checkip-path = /\n")
		buf.WriteString("    checkip-ssl = true\n")
		buf.WriteString("    ttl = 300\n")
		buf.WriteString("    proxied = false\n")
		buf.WriteString("}\n")
	default:
		return "", fmt.Errorf("unsupported dynamic DNS provider %q", cfg.Cloudflare.DDNSProvider)
	}

	return buf.String(), nil
}

// GenerateCloudflareDDNS is retained as a source-compatible wrapper for the
// existing apply pipeline. The generated configuration is provider-aware.
func GenerateCloudflareDDNS(cfg *config.SystemConfig) (string, error) {
	return GenerateDynamicDNS(cfg)
}

// GenerateCloudflareTunnel emits only non-secret metadata for a remotely
// managed Cloudflare Tunnel. The privileged runtime writes the connector token
// to a root-only token file and cloudflared consumes it with --token-file.
// Public-hostname routing remains owned by Cloudflare, so this file never
// contains credentials, local tunnel IDs, or an ingress rule that can drift
// from the remotely managed configuration.
func GenerateCloudflareTunnel(cfg *config.SystemConfig) (string, error) {
	if !cfg.Cloudflare.TunnelEnabled {
		return "# Cloudflare Tunnel disabled\n", nil
	}
	if strings.TrimSpace(cfg.Cloudflare.TunnelHostname) == "" {
		return "", fmt.Errorf("Cloudflare Tunnel hostname is required")
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — remotely managed Cloudflare Tunnel\n")
	buf.WriteString("# Routing and origin settings are managed in Cloudflare.\n")
	buf.WriteString("# Expected public hostname: " + strings.TrimSpace(cfg.Cloudflare.TunnelHostname) + "\n")
	buf.WriteString("# Connector token is stored separately and is never written here.\n")
	return buf.String(), nil
}
