package services

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// GenerateDnsmasq renders dnsmasq DHCP & DNS server configuration.
func GenerateDnsmasq(cfg *config.SystemConfig) (string, error) {
	runtimeCfg := *cfg
	runtimeCfg.LAN.Interface = cfg.RuntimeLANInterface()
	cfg = &runtimeCfg

	var buf bytes.Buffer

	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString("# File: /etc/dnsmasq.d/minimalrouter.conf\n\n")

	// Domain & Interface binding
	buf.WriteString(fmt.Sprintf("domain=%s\n", cfg.System.Domain))
	buf.WriteString(fmt.Sprintf("interface=%s\n", cfg.LAN.Interface))
	buf.WriteString(fmt.Sprintf("listen-address=127.0.0.1,%s\n", cfg.LAN.IPAddress))
	buf.WriteString("bind-interfaces\n")
	buf.WriteString("no-resolv\n")
	buf.WriteString("strict-order\n")
	buf.WriteString("cache-size=1000\n")
	buf.WriteString("bogus-priv\n")
	buf.WriteString("domain-needed\n")
	buf.WriteString("# pfSense Security Hardening: DNS Rebind Attack Protection\n")
	buf.WriteString("stop-dns-rebind\n")
	buf.WriteString("rebind-domain-ok=/use-application-dns.net/\n\n")

	// Upstream DNS Servers
	if len(cfg.DHCP.DNSServers) > 0 {
		buf.WriteString("# Upstream DNS Servers\n")
		for _, dns := range cfg.DHCP.DNSServers {
			buf.WriteString(fmt.Sprintf("server=%s\n", dns))
		}
		buf.WriteString("\n")
	}

	// DNS-over-HTTPS integration: redirect upstream to local proxy
	if cfg.DHCP.DNSEnabled {
		buf.WriteString(GenerateDoHDnsmasqIntegration(cfg))
	}

	// DHCP Server settings
	if cfg.DHCP.Enabled {
		buf.WriteString("# DHCP Pool\n")
		buf.WriteString(fmt.Sprintf("dhcp-range=%s,%s,%s,%s\n",
			cfg.DHCP.RangeStart,
			cfg.DHCP.RangeEnd,
			cfg.LAN.Netmask,
			cfg.DHCP.LeaseTime,
		))
		buf.WriteString(fmt.Sprintf("dhcp-option=option:router,%s\n", cfg.LAN.IPAddress))
		buf.WriteString(fmt.Sprintf("dhcp-option=option:dns-server,%s\n\n", cfg.LAN.IPAddress))

		// Static Leases
		if len(cfg.DHCP.StaticLeases) > 0 {
			buf.WriteString("# Static DHCP Leases\n")
			for _, lease := range cfg.DHCP.StaticLeases {
				hostname := strings.TrimSpace(lease.Hostname)
				if hostname != "" {
					buf.WriteString(fmt.Sprintf("dhcp-host=%s,%s,%s\n", lease.MAC, lease.IPAddress, hostname))
				} else {
					buf.WriteString(fmt.Sprintf("dhcp-host=%s,%s\n", lease.MAC, lease.IPAddress))
				}
			}
		}
	} else {
		buf.WriteString("# DHCP Disabled\n")
	}

	// AdGuard Home & Content Filter integration
	if cfg.AdGuard.Enabled {
		buf.WriteString("\n# AdGuard DNS Sinkhole Blocklist\n")
		buf.WriteString("conf-file=/etc/dnsmasq.d/adblock_hosts.conf\n")

	}

	return buf.String(), nil
}

// ServiceDomains maps service identifiers to domain names for content filtering.
var ServiceDomains = map[string][]string{
	"youtube":  {"youtube.com", "googlevideo.com", "ytimg.com", "youtu.be"},
	"tiktok":   {"tiktok.com", "byteoversea.com", "ibytedtos.com", "tiktokv.com"},
	"facebook": {"facebook.com", "instagram.com", "fbcdn.net", "messenger.com"},
	"adult":    {"pornhub.com", "xvideos.com", "xnxx.com", "onlyfans.com"},
	"gaming":   {"roblox.com", "twitch.tv", "steamcommunity.com", "epicgames.com"},
}
