package services

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

func writeStaticLeases(buf *bytes.Buffer, heading, tag string, leases []config.StaticLease) {
	if len(leases) == 0 {
		return
	}
	buf.WriteString(heading + "\n")
	for _, lease := range leases {
		hostname := strings.TrimSpace(lease.Hostname)
		parts := []string{lease.MAC}
		if tag != "" {
			parts = append(parts, "set:"+tag)
		}
		parts = append(parts, lease.IPAddress)
		if hostname != "" {
			parts = append(parts, hostname)
		}
		buf.WriteString("dhcp-host=" + strings.Join(parts, ",") + "\n")
	}
}

// GenerateDnsmasq renders dnsmasq DHCP & DNS server configuration.
func GenerateDnsmasq(cfg *config.SystemConfig) (string, error) {
	runtimeCfg := *cfg
	runtimeCfg.LAN.Interface = cfg.RuntimeLANInterface()
	cfg = &runtimeCfg

	var buf bytes.Buffer

	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString("# File: /etc/dnsmasq.d/minimalrouter.conf\n\n")

	// Domain & interface binding. The IoT interface is a separate routed zone;
	// management HTTPS is never opened there by the firewall.
	buf.WriteString(fmt.Sprintf("domain=%s\n", cfg.System.Domain))
	buf.WriteString(fmt.Sprintf("interface=%s\n", cfg.LAN.Interface))
	listenAddresses := []string{"127.0.0.1", cfg.LAN.IPAddress}
	if cfg.IoT.Enabled {
		buf.WriteString(fmt.Sprintf("interface=%s\n", cfg.RuntimeIoTInterface()))
		listenAddresses = append(listenAddresses, cfg.IoT.IPAddress)
	}
	buf.WriteString(fmt.Sprintf("listen-address=%s\n", strings.Join(listenAddresses, ",")))
	buf.WriteString("bind-interfaces\n")
	buf.WriteString("no-resolv\n")
	buf.WriteString("strict-order\n")
	buf.WriteString("cache-size=1000\n")
	buf.WriteString("bogus-priv\n")
	buf.WriteString("domain-needed\n")
	buf.WriteString("stop-dns-rebind\n")
	buf.WriteString("rebind-domain-ok=/use-application-dns.net/\n\n")

	if len(cfg.DHCP.DNSServers) > 0 {
		buf.WriteString("# Upstream DNS servers\n")
		for _, dns := range cfg.DHCP.DNSServers {
			buf.WriteString(fmt.Sprintf("server=%s\n", dns))
		}
		buf.WriteString("\n")
	}

	if cfg.DHCP.DNSEnabled {
		buf.WriteString(GenerateDoHDnsmasqIntegration(cfg))
	}

	if cfg.DHCP.Enabled || (cfg.IoT.Enabled && cfg.IoT.DHCP.Enabled) {
		buf.WriteString("dhcp-leasefile=/run/minimalrouter/dnsmasq.leases\n")
	}

	if cfg.DHCP.Enabled {
		buf.WriteString("\n# Main LAN DHCP pool\n")
		buf.WriteString(fmt.Sprintf("dhcp-range=set:lan,%s,%s,%s,%s\n",
			cfg.DHCP.RangeStart,
			cfg.DHCP.RangeEnd,
			cfg.LAN.Netmask,
			cfg.DHCP.LeaseTime,
		))
		buf.WriteString(fmt.Sprintf("dhcp-option=tag:lan,option:router,%s\n", cfg.LAN.IPAddress))
		buf.WriteString(fmt.Sprintf("dhcp-option=tag:lan,option:dns-server,%s\n", cfg.LAN.IPAddress))
		writeStaticLeases(&buf, "# Main LAN static DHCP leases", "lan", cfg.DHCP.StaticLeases)
	} else {
		buf.WriteString("\n# Main LAN DHCP disabled\n")
	}

	if cfg.IoT.Enabled {
		if cfg.IoT.DHCP.Enabled {
			buf.WriteString("\n# Isolated IoT DHCP pool\n")
			buf.WriteString(fmt.Sprintf("dhcp-range=set:iot,%s,%s,%s,%s\n",
				cfg.IoT.DHCP.RangeStart,
				cfg.IoT.DHCP.RangeEnd,
				cfg.IoT.Netmask,
				cfg.IoT.DHCP.LeaseTime,
			))
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:iot,option:router,%s\n", cfg.IoT.IPAddress))
			buf.WriteString(fmt.Sprintf("dhcp-option=tag:iot,option:dns-server,%s\n", cfg.IoT.IPAddress))
			writeStaticLeases(&buf, "# IoT static DHCP leases", "iot", cfg.IoT.DHCP.StaticLeases)
		} else {
			buf.WriteString("\n# IoT DHCP disabled\n")
		}
	}

	if cfg.AdGuard.Enabled {
		buf.WriteString("\n# Global DNS sinkhole blocklist\n")
		buf.WriteString("conf-file=/etc/dnsmasq.d/adblock_hosts.conf\n")
	}
	buf.WriteString(GeneratePolicyDNSConfig(cfg))

	return buf.String(), nil
}

// ServiceDomains is retained for API compatibility with the early dashboard.
// New scheduled allowlists use PolicyServiceDomains in device_policy.go.
var ServiceDomains = map[string][]string{
	"youtube":  {"youtube.com", "googlevideo.com", "ytimg.com", "youtu.be"},
	"tiktok":   {"tiktok.com", "byteoversea.com", "ibytedtos.com", "tiktokv.com"},
	"facebook": {"facebook.com", "instagram.com", "fbcdn.net", "messenger.com"},
	"adult":    {"pornhub.com", "xvideos.com", "xnxx.com", "onlyfans.com"},
	"gaming":   {"roblox.com", "twitch.tv", "steamcommunity.com", "epicgames.com"},
	"steam":    PolicyServiceDomains["steam"],
}
