package services

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// GenerateDnsmasq renders dnsmasq DHCP & DNS server configuration.
func GenerateDnsmasq(cfg *config.SystemConfig) (string, error) {
	runtimeCfg := *cfg
	runtimeCfg.LAN.Interface = cfg.RuntimeLANInterface()
	cfg = &runtimeCfg

	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString("# File: /etc/dnsmasq.d/minimalrouter.conf\n\n")
	buf.WriteString(fmt.Sprintf("domain=%s\n", cfg.System.Domain))
	buf.WriteString(fmt.Sprintf("interface=%s\n", cfg.LAN.Interface))
	listenAddresses := []string{"127.0.0.1", cfg.LAN.IPAddress}
	// The firewall intentionally exposes DNS to authenticated wg0 peers. Bind
	// dnsmasq to the tunnel as well so policy and service availability agree;
	// ExtraLAN remains deliberately absent and therefore hosts no DNS service.
	if cfg.WireGuard.Enabled && cfg.WireGuard.Interface != "" && cfg.WireGuard.Address != "" {
		wgIP := strings.SplitN(cfg.WireGuard.Address, "/", 2)[0]
		if wgIP != "" {
			buf.WriteString(fmt.Sprintf("interface=%s\n", cfg.WireGuard.Interface))
			listenAddresses = append(listenAddresses, wgIP)
		}
	}
	buf.WriteString(fmt.Sprintf("listen-address=%s\n", strings.Join(listenAddresses, ",")))
	// bind-dynamic keeps the same explicit interface/listen-address allowlist as
	// bind-interfaces, but on Linux it tolerates a WireGuard interface/address
	// appearing after dnsmasq starts. Cold boot, wg0 enable/disable, and rollback
	// therefore cannot fail only because service ordering briefly leaves wg0
	// absent. nftables remains the independent packet-filter boundary.
	buf.WriteString("bind-dynamic\n")
	buf.WriteString("no-resolv\n")
	buf.WriteString("strict-order\n")
	buf.WriteString("cache-size=1000\n")
	buf.WriteString("bogus-priv\n")
	buf.WriteString("domain-needed\n")
	buf.WriteString("# DNS rebind attack protection\n")
	buf.WriteString("stop-dns-rebind\n")
	buf.WriteString("rebind-domain-ok=/use-application-dns.net/\n\n")

	if len(cfg.DHCP.DNSServers) > 0 {
		buf.WriteString("# Upstream DNS servers\n")
		for _, dns := range cfg.DHCP.DNSServers {
			buf.WriteString(fmt.Sprintf("server=%s\n", dns))
		}
		buf.WriteString("\n")
	}
	if cfg.DHCP.DNSEnabled {
		buf.WriteString(GenerateDoHDnsmasqIntegration(cfg))
	}

	if cfg.DHCP.Enabled {
		buf.WriteString("# DHCP pool\n")
		// Keep leases across appliance reboots in a dnsmasq-owned directory,
		// separate from routerd's 0700 canonical config/auth store.
		buf.WriteString("dhcp-leasefile=/var/lib/minimalrouter-dhcp/dnsmasq.leases\n")
		buf.WriteString(fmt.Sprintf("dhcp-range=%s,%s,%s,%s\n", cfg.DHCP.RangeStart, cfg.DHCP.RangeEnd, cfg.LAN.Netmask, cfg.DHCP.LeaseTime))
		buf.WriteString(fmt.Sprintf("dhcp-option=option:router,%s\n", cfg.LAN.IPAddress))
		buf.WriteString(fmt.Sprintf("dhcp-option=option:dns-server,%s\n\n", cfg.LAN.IPAddress))
		if len(cfg.DHCP.StaticLeases) > 0 {
			buf.WriteString("# Static DHCP leases\n")
			for _, lease := range cfg.DHCP.StaticLeases {
				hostname := strings.TrimSpace(lease.Hostname)
				if hostname != "" {
					buf.WriteString(fmt.Sprintf("dhcp-host=%s,%s,%s\n", lease.MAC, lease.IPAddress, hostname))
				} else {
					buf.WriteString(fmt.Sprintf("dhcp-host=%s,%s\n", lease.MAC, lease.IPAddress))
				}
			}
		}
	} else {
		buf.WriteString("# DHCP disabled\n")
	}

	if len(cfg.DNS.Records) > 0 {
		buf.WriteString("\n# Static DNS records\n")
		for _, rec := range cfg.DNS.Records {
			buf.WriteString(fmt.Sprintf("host-record=%s,%s\n", rec.Name, rec.IP))
		}
	}

	if cfg.AdGuard.Enabled {
		buf.WriteString("\n# DNS Filter global sinkhole blocklist\n")
		buf.WriteString("conf-file=/etc/dnsmasq.d/adblock_hosts.conf\n")
	}
	writeDNSFilterNftsets(&buf, cfg)
	return buf.String(), nil
}

// ServiceDomains maps stable service identifiers to domains whose resolved
// IPv4 destinations are inserted into nftables sets by dnsmasq.
var ServiceDomains = map[string][]string{
	"youtube":   {"youtube.com", "googlevideo.com", "ytimg.com", "youtu.be"},
	"steam":     {"steampowered.com", "steamcommunity.com", "steamstatic.com", "steamcontent.com", "steamserver.net"},
	"wiki":      {"wikipedia.org", "wikimedia.org", "wikimediafoundation.org", "mediawiki.org"},
	"tiktok":    {"tiktok.com", "byteoversea.com", "ibytedtos.com", "tiktokv.com"},
	"instagram": {"instagram.com", "cdninstagram.com"},
	"facebook":  {"facebook.com", "fbcdn.net", "messenger.com"},
	"roblox":    {"roblox.com", "rbxcdn.com"},
	"epic":      {"epicgames.com", "unrealengine.com"},
	"twitch":    {"twitch.tv", "ttvnw.net", "jtvnw.net"},
	"adult":     {"pornhub.com", "xvideos.com", "xnxx.com", "onlyfans.com"},
	"gaming":    {"roblox.com", "rbxcdn.com", "twitch.tv", "ttvnw.net", "steampowered.com", "steamcommunity.com", "epicgames.com"},
}
