package services

import (
	"bytes"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// GenerateDoHProxy produces a cloudflared DNS-over-HTTPS proxy configuration
// that listens on localhost and forwards encrypted DNS queries to upstream providers.
// When enabled, dnsmasq upstream servers are pointed to the local proxy.
func GenerateDoHProxy(cfg *config.SystemConfig) (string, error) {
	if !cfg.DHCP.DNSEnabled {
		return "# DNS-over-HTTPS proxy disabled (DNS not enabled)\n", nil
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — DNS-over-HTTPS proxy\n")
	buf.WriteString("# Uses cloudflared as a local DoH/TLS forwarding proxy\n\n")

	// Local proxy listens on 127.0.0.1:5053 to avoid conflicts with dnsmasq on 53
	buf.WriteString("# cloudflared DoH proxy configuration\n")
	buf.WriteString("proxy-dns: true\n")
	buf.WriteString("proxy-dns-address: 127.0.0.1:5053\n")
	buf.WriteString("proxy-dns-port: 5053\n\n")

	buf.WriteString("# Upstream DNS-over-HTTPS resolvers\n")
	buf.WriteString("# Cloudflare (1.1.1.1) — primary\n")
	buf.WriteString("proxy-dns-upstream:\n")
	buf.WriteString("  - https://1.1.1.1/dns-query\n")
	buf.WriteString("  - https://1.0.0.1/dns-query\n")
	buf.WriteString("  - https://dns.google/dns-query\n")
	buf.WriteString("  - https://dns.quad9.net/dns-query\n\n")

	buf.WriteString("# TLS session caching for performance\n")
	buf.WriteString("tls-cipher-suites: TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256\n")
	buf.WriteString("edns-payload-size: 1232\n")

	return buf.String(), nil
}

// GenerateDoHDnsmasqIntegration produces dnsmasq config lines that point
// upstream DNS to the local DoH proxy instead of directly to remote servers.
func GenerateDoHDnsmasqIntegration(cfg *config.SystemConfig) string {
	if !cfg.DHCP.DNSEnabled {
		return ""
	}

	var buf bytes.Buffer
	buf.WriteString("# ── DNS-over-HTTPS Integration ──\n")
	buf.WriteString("# Point dnsmasq upstream to local DoH proxy\n")
	buf.WriteString("server=127.0.0.1#5053\n")

	return buf.String()
}
