package services

import (
	"bytes"
	"fmt"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// GenerateHostapd renders the WPA2/WPA3 /etc/hostapd/hostapd.conf configuration file.
func GenerateHostapd(cfg *config.SystemConfig) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString("# File: /etc/hostapd/hostapd.conf\n\n")

	if !cfg.WiFi.Enabled {
		buf.WriteString("# Wi-Fi Access Point is disabled\n")
		return buf.String(), nil
	}

	iface := cfg.WiFi.Interface
	if iface == "" {
		iface = "wlan0"
	}

	buf.WriteString(fmt.Sprintf("interface=%s\n", iface))
	buf.WriteString(fmt.Sprintf("bridge=%s\n", config.WiFiBridgeInterface))
	buf.WriteString("driver=nl80211\n")
	buf.WriteString(fmt.Sprintf("ssid=%s\n", cfg.WiFi.SSID))

	// Hardware mode & band
	if cfg.WiFi.Band == "5ghz" {
		buf.WriteString("hw_mode=a\n")
		buf.WriteString("ieee80211n=1\n")
		buf.WriteString("ieee80211ac=1\n")
	} else {
		buf.WriteString("hw_mode=g\n")
		buf.WriteString("ieee80211n=1\n")
	}

	channel := cfg.WiFi.Channel
	if channel <= 0 {
		channel = 36
	}
	buf.WriteString(fmt.Sprintf("channel=%d\n", channel))

	if cfg.WiFi.HideSSID {
		buf.WriteString("ignore_broadcast_ssid=1\n")
	} else {
		buf.WriteString("ignore_broadcast_ssid=0\n")
	}

	// WPA2/WPA3 transition mode with protected management frames. TKIP is
	// intentionally forbidden.
	buf.WriteString("wpa=2\n")
	buf.WriteString(fmt.Sprintf("wpa_passphrase=%s\n", cfg.WiFi.Passphrase))
	buf.WriteString("wpa_key_mgmt=WPA-PSK SAE\n")
	buf.WriteString("ieee80211w=1\n")
	buf.WriteString("rsn_pairwise=CCMP\n")

	return buf.String(), nil
}
