package services

import (
	"bytes"
	"fmt"
	"net"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// GenerateNftables renders an atomic, deterministic nftables configuration string.
func GenerateNftables(cfg *config.SystemConfig) (string, error) {
	runtimeCfg := *cfg
	runtimeCfg.LAN.Interface = cfg.RuntimeLANInterface()
	cfg = &runtimeCfg

	var buf bytes.Buffer

	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString("# Table: inet minimalrouter\n\n")

	// router-applyd wraps this owned table in an atomic delete-and-create batch.
	buf.WriteString("table inet minimalrouter {\n")
	writeDeviceProfileObjects(&buf, cfg)

	// Input Chain
	buf.WriteString("  chain input {\n")
	buf.WriteString("    type filter hook input priority filter; policy drop;\n\n")
	buf.WriteString("    # Allow loopback\n")
	buf.WriteString("    iifname \"lo\" accept\n\n")

	if cfg.WAN.Interface != "" {
		buf.WriteString("    # Drop spoofed/reserved WAN sources before connection tracking accepts\n")
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" ip saddr { 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/3 } drop\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" fib saddr . iif oif missing drop\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" meta nfproto ipv6 drop\n", cfg.WAN.Interface))
		buf.WriteString("    iifname \"ppp*\" ip saddr { 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/3 } drop\n")
		buf.WriteString("    iifname \"ppp*\" fib saddr . iif oif missing drop\n")
		buf.WriteString("    iifname \"ppp*\" meta nfproto ipv6 drop\n\n")
	}
	if cfg.LAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    # LAN source anti-spoofing (0.0.0.0 is needed for DHCP discovery)\n    iifname \"%s\" ip saddr != { 0.0.0.0, %s } drop\n\n", cfg.LAN.Interface, cfg.LAN.CIDR))
	}

	// Invalid packets must be rejected before any service-specific accept rule.
	buf.WriteString("    # Reject invalid packets before service accepts\n")
	buf.WriteString("    ct state invalid drop\n")
	
	// Custom DENY input rules run before established state to cut existing connections
	for _, rule := range cfg.Firewall.CustomRules {
		if !rule.Enabled || rule.Direction != "input" || rule.Action != "deny" {
			continue
		}
		match := []string{fmt.Sprintf("iifname \"%s\"", cfg.LAN.Interface)}
		if rule.SrcIP != "" {
			match = append(match, "ip saddr "+rule.SrcIP)
		}
		if rule.Protocol != "any" {
			match = append(match, rule.Protocol)
		}
		if rule.Protocol == "tcp" || rule.Protocol == "udp" {
			match = append(match, fmt.Sprintf("dport %d", rule.DstPort))
		}
		buf.WriteString(fmt.Sprintf("    # Custom LAN input deny rule: %s\n", rule.Name))
		buf.WriteString(fmt.Sprintf("    %s drop\n", strings.Join(match, " ")))
	}
	
	buf.WriteString("    # Allow established and related connections\n")
	buf.WriteString("    ct state established,related accept\n\n")

	if cfg.WireGuard.Enabled {
		_, wgNetwork, _ := net.ParseCIDR(cfg.WireGuard.Address)
		buf.WriteString("    # WireGuard endpoint with a per-source flood guard\n")
		if cfg.WAN.Interface != "" {
			buf.WriteString(fmt.Sprintf("    iifname \"%s\" udp dport %d ct state new meter wg_wan_rate { ip saddr timeout 10s limit rate over 20/second burst 40 packets } drop\n", cfg.WAN.Interface, cfg.WireGuard.ListenPort))
			buf.WriteString(fmt.Sprintf("    iifname \"%s\" udp dport %d accept\n", cfg.WAN.Interface, cfg.WireGuard.ListenPort))
		}
		buf.WriteString(fmt.Sprintf("    iifname \"ppp*\" udp dport %d ct state new meter wg_ppp_rate { ip saddr timeout 10s limit rate over 20/second burst 40 packets } drop\n", cfg.WireGuard.ListenPort))
		buf.WriteString(fmt.Sprintf("    iifname \"ppp*\" udp dport %d accept\n", cfg.WireGuard.ListenPort))
		buf.WriteString("    # Authenticated tunnel services\n")
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" ip saddr != %s drop\n", cfg.WireGuard.Interface, wgNetwork.String()))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" tcp dport %d accept\n", cfg.WireGuard.Interface, cfg.System.HTTPSPort))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" udp dport 53 accept\n", cfg.WireGuard.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" tcp dport 53 accept\n\n", cfg.WireGuard.Interface))
	}

	// Allow Squid Proxy if enabled (LAN input only)
	if cfg.SquidProxy.Enabled {
		port := cfg.SquidProxy.Port
		if port == 0 {
			port = 3128
		}
		if cfg.LAN.Interface != "" {
			buf.WriteString(fmt.Sprintf("    # Allow Squid Proxy from LAN (%s, port %d)\n", cfg.LAN.Interface, port))
			buf.WriteString(fmt.Sprintf("    iifname \"%s\" tcp dport %d accept\n\n", cfg.LAN.Interface, port))
		}
	}

	// LAN input is restricted to explicitly owned management/network services.
	if cfg.LAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    # Allow essential network services from LAN (%s) only\n", cfg.LAN.Interface))
		if cfg.System.ManagementAccess != "wireguard_only" {
			buf.WriteString(fmt.Sprintf("    iifname \"%s\" tcp dport %d ct state new limit rate over 30/second burst 60 packets drop\n", cfg.LAN.Interface, cfg.System.HTTPSPort))
			buf.WriteString(fmt.Sprintf("    iifname \"%s\" tcp dport %d accept\n", cfg.LAN.Interface, cfg.System.HTTPSPort))
		} else {
			buf.WriteString("    # Management HTTPS is intentionally unavailable on LAN; use WireGuard\n")
		}
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" udp dport { 53, 67 } accept\n", cfg.LAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" tcp dport 53 accept\n", cfg.LAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" ip protocol icmp accept\n\n", cfg.LAN.Interface))
	}
	if cfg.WireGuard.Enabled {
		_, wgNetwork, _ := net.ParseCIDR(cfg.WireGuard.Address)
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" ip saddr != %s drop\n\n", cfg.WireGuard.Interface, wgNetwork.String()))
	}

	// Optional input rules are still confined to the LAN interface. A custom
	// rule can never make a router-local service reachable from WAN.
	for _, rule := range cfg.Firewall.CustomRules {
		if !rule.Enabled || rule.Direction != "input" || rule.Action != "allow" {
			continue
		}
		match := []string{fmt.Sprintf("iifname \"%s\"", cfg.LAN.Interface)}
		if rule.SrcIP != "" {
			match = append(match, "ip saddr "+rule.SrcIP)
		}
		if rule.Protocol != "any" {
			match = append(match, rule.Protocol)
		}
		if rule.Protocol == "tcp" || rule.Protocol == "udp" {
			match = append(match, fmt.Sprintf("dport %d", rule.DstPort))
		}
		buf.WriteString(fmt.Sprintf("    # Custom LAN input allow rule: %s\n", rule.Name))
		buf.WriteString(fmt.Sprintf("    %s accept\n", strings.Join(match, " ")))
	}

	buf.WriteString("    # Reject WAN unsolicited input\n")
	buf.WriteString("    drop\n")
	buf.WriteString("  }\n\n")

	// Forward Chain
	buf.WriteString("  chain forward {\n")
	buf.WriteString("    type filter hook forward priority filter; policy drop;\n\n")
	if cfg.WAN.Interface != "" {
		buf.WriteString("    # WAN anti-spoofing precedes state acceptance\n")
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" ip saddr { 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/3 } drop\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" fib saddr . iif oif missing drop\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" meta nfproto ipv6 drop\n", cfg.WAN.Interface))
		buf.WriteString("    iifname \"ppp*\" ip saddr { 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/3 } drop\n")
		buf.WriteString("    iifname \"ppp*\" fib saddr . iif oif missing drop\n")
		buf.WriteString("    iifname \"ppp*\" meta nfproto ipv6 drop\n\n")
	}
	if cfg.LAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" ip saddr != %s drop\n\n", cfg.LAN.Interface, cfg.LAN.CIDR))
	}
	buf.WriteString("    # Reject invalid before established state\n")
	buf.WriteString("    ct state invalid drop\n")
	if len(activeManagedServices(cfg)) > 0 {
		buf.WriteString("    # Device schedules run before established acceptance so expired streams are cut\n")
		buf.WriteString("    jump device_profiles\n")
	}
	
	// Custom DENY forward rules run before established state
	for _, rule := range cfg.Firewall.CustomRules {
		if !rule.Enabled || rule.Direction != "forward" || rule.Action != "deny" {
			continue
		}
		match := []string{fmt.Sprintf("iifname \"%s\"", cfg.LAN.Interface)}
		if rule.SrcIP != "" {
			match = append(match, "ip saddr "+rule.SrcIP)
		}
		if rule.Protocol != "any" {
			match = append(match, rule.Protocol)
		}
		if rule.Protocol == "tcp" || rule.Protocol == "udp" {
			match = append(match, fmt.Sprintf("dport %d", rule.DstPort))
		}
		buf.WriteString(fmt.Sprintf("    # Custom LAN forward deny rule: %s\n", rule.Name))
		buf.WriteString(fmt.Sprintf("    %s drop\n", strings.Join(match, " ")))
	}
	
	buf.WriteString("    # Allow established/related\n")
	buf.WriteString("    ct state established,related accept\n\n")

	buf.WriteString("    # TCP MSS clamping prevents PPPoE fragmentation stalls\n")
	buf.WriteString("    tcp flags syn tcp option maxseg size set rt mtu\n\n")

	// Block direct WAN access for Restricted IP Alias (Forced through Squid Proxy)
	if cfg.SquidProxy.Enabled && len(cfg.SquidProxy.RestrictedIPs) > 0 {
		buf.WriteString("    # Block direct WAN traffic for Restricted IP Alias (Must use Squid Proxy)\n")
		for _, item := range cfg.SquidProxy.RestrictedIPs {
			ip := strings.TrimSpace(item.IPAddress)
			if ip != "" && item.Enabled {
				buf.WriteString(fmt.Sprintf("    ip saddr %s drop\n", ip))
			}
		}
		buf.WriteString("\n")
	}

	// Custom rules can only govern traffic originating on the LAN.
	for _, rule := range cfg.Firewall.CustomRules {
		if !rule.Enabled || rule.Direction != "forward" || rule.Action != "allow" {
			continue
		}
		match := []string{fmt.Sprintf("iifname \"%s\"", cfg.LAN.Interface)}
		if rule.SrcIP != "" {
			match = append(match, "ip saddr "+rule.SrcIP)
		}
		if rule.Protocol != "any" {
			match = append(match, rule.Protocol)
		}
		if rule.Protocol == "tcp" || rule.Protocol == "udp" {
			match = append(match, fmt.Sprintf("dport %d", rule.DstPort))
		}
		buf.WriteString(fmt.Sprintf("    # Custom LAN forward allow rule: %s\n", rule.Name))
		buf.WriteString(fmt.Sprintf("    %s accept\n", strings.Join(match, " ")))
	}

	if cfg.WAN.Enabled && cfg.LAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    # Allow LAN (%s) out to WAN\n", cfg.LAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" oifname \"%s\" accept\n", cfg.LAN.Interface, cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" oifname \"ppp*\" accept\n\n", cfg.LAN.Interface))
	}
	if cfg.WireGuard.Enabled {
		buf.WriteString("    # Authenticated WireGuard clients may reach LAN and optional full-tunnel WAN\n")
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" oifname \"%s\" accept\n", cfg.WireGuard.Interface, cfg.LAN.Interface))
		if cfg.WAN.Enabled {
			buf.WriteString(fmt.Sprintf("    iifname \"%s\" oifname \"%s\" accept\n", cfg.WireGuard.Interface, cfg.WAN.Interface))
			buf.WriteString(fmt.Sprintf("    iifname \"%s\" oifname \"ppp*\" accept\n", cfg.WireGuard.Interface))
		}
		buf.WriteString("\n")
	}

	buf.WriteString("  }\n\n")

	// Output Chain
	buf.WriteString("  chain output {\n")
	buf.WriteString("    type filter hook output priority filter; policy drop;\n\n")
	buf.WriteString("    # The appliance itself has a narrow egress allowlist\n")
	buf.WriteString("    oifname \"lo\" accept\n")
	if cfg.WAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    # Never leak private, loopback, CGNAT, or multicast source addresses to WAN (%s)\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    oifname \"%s\" ip saddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8, 0.0.0.0/8, 100.64.0.0/10, 224.0.0.0/4 } drop\n", cfg.WAN.Interface))
		buf.WriteString("    oifname \"ppp*\" ip saddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8, 0.0.0.0/8, 100.64.0.0/10, 224.0.0.0/4 } drop\n")
	}
	buf.WriteString("    ct state invalid drop\n")
	buf.WriteString("    ct state established,related accept\n")
	buf.WriteString(fmt.Sprintf("    oifname \"%s\" udp sport { 53, 67 } accept\n", cfg.LAN.Interface))
	if cfg.System.ManagementAccess == "wireguard_only" {
		buf.WriteString(fmt.Sprintf("    oifname \"%s\" tcp sport 53 accept\n", cfg.LAN.Interface))
	} else {
		buf.WriteString(fmt.Sprintf("    oifname \"%s\" tcp sport { 53, %d } accept\n", cfg.LAN.Interface, cfg.System.HTTPSPort))
	}
	if cfg.WireGuard.Enabled {
		buf.WriteString(fmt.Sprintf("    oifname \"%s\" udp sport { 53, %d } accept\n", cfg.WireGuard.Interface, cfg.WireGuard.ListenPort))
		buf.WriteString(fmt.Sprintf("    oifname \"%s\" tcp sport { 53, %d } accept\n", cfg.WireGuard.Interface, cfg.System.HTTPSPort))
	}
	if len(cfg.DHCP.DNSServers) > 0 {
		buf.WriteString(fmt.Sprintf("    ip daddr { %s } udp dport 53 accept\n", strings.Join(cfg.DHCP.DNSServers, ", ")))
		buf.WriteString(fmt.Sprintf("    ip daddr { %s } tcp dport 53 accept\n", strings.Join(cfg.DHCP.DNSServers, ", ")))
	}
	buf.WriteString("    udp dport 123 accept\n")
	buf.WriteString("    ip protocol icmp accept\n\n")
	if cfg.Cloudflare.DDNSEnabled {
		buf.WriteString("    # Cloudflare DDNS needs HTTPS for the root-run verification and inadyn daemon\n")
		buf.WriteString("    meta skuid root tcp dport 443 accept\n")
		buf.WriteString("    meta skuid inadyn tcp dport 443 accept\n")
	}
	if cfg.SquidProxy.Enabled {
		buf.WriteString("    # Only the unprivileged Squid account may open web connections\n")
		buf.WriteString("    meta skuid squid tcp dport { 80, 443 } accept\n")
	}
	buf.WriteString("    counter drop\n")
	buf.WriteString("  }\n\n")

	// Postrouting (Masquerade NAT)
	buf.WriteString("  chain postrouting {\n")
	buf.WriteString("    type nat hook postrouting priority srcnat; policy accept;\n\n")
	buf.WriteString("    # Masquerade outgoing LAN traffic on WAN interfaces (ppp0 / ethernet WAN)\n")
	if cfg.WAN.Enabled {
		buf.WriteString("    oifname \"ppp*\" masquerade\n")
		buf.WriteString(fmt.Sprintf("    oifname \"%s\" masquerade\n", cfg.WAN.Interface))
	}
	buf.WriteString("  }\n")

	buf.WriteString("}\n")

	return buf.String(), nil
}
