package services

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// GenerateNftables renders an atomic, deterministic nftables configuration string.
func GenerateNftables(cfg *config.SystemConfig) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString("# Table: inet minimalrouter\n\n")

	// Flush existing table to guarantee atomic replace
	buf.WriteString("table inet minimalrouter {\n")

	// Input Chain
	buf.WriteString("  chain input {\n")
	buf.WriteString("    type filter hook input priority filter; policy drop;\n\n")
	buf.WriteString("    # Allow loopback\n")
	buf.WriteString("    iifname \"lo\" accept\n\n")
	buf.WriteString("    # Allow established and related connections\n")
	buf.WriteString("    ct state established,related accept\n")
	buf.WriteString("    ct state invalid drop\n\n")

	// Allow Squid Proxy if enabled (LAN input only)
	if cfg.SquidProxy.Enabled {
		port := cfg.SquidProxy.Port
		if port == 0 {
			port = 3128
		}
		if cfg.LAN.Interface != "" {
			buf.WriteString(fmt.Sprintf("    # Allow Squid Proxy from LAN (%s, port %d)\n", cfg.LAN.Interface, port))
			buf.WriteString(fmt.Sprintf("    iifname \"%s\" tcp dport %d accept\n\n", cfg.LAN.Interface, port))
		}
	}

	// LAN Input permissions
	if cfg.LAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    # Allow all management and services from LAN (%s)\n", cfg.LAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" accept\n\n", cfg.LAN.Interface))
	}

	// pfSense Security Hardening: Block Bogons, CGNAT, Multicast & Private RFC1918 spoofing on WAN
	if cfg.WAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    # pfSense Hardening: Block RFC1918, CGNAT, Multicast & spoofed source IPs on WAN (%s)\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" ip saddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8, 0.0.0.0/8, 100.64.0.0/10, 224.0.0.0/4 } drop\n\n", cfg.WAN.Interface))

		buf.WriteString(fmt.Sprintf("    # pfSense Hardening: uRPF Strict Anti-Spoofing on WAN (%s)\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" fib saddr . iif oif missing drop\n\n", cfg.WAN.Interface))

		buf.WriteString(fmt.Sprintf("    # pfSense Hardening: Block IPv6 WAN input except required ICMPv6 Discovery (%s)\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" ip6 nexthdr ipv6-icmp icmpv6 type { nd-neighbor-solicit, nd-router-advert, nd-neighbor-advert, packet-too-big } accept\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" ip6 drop\n\n", cfg.WAN.Interface))

		buf.WriteString(fmt.Sprintf("    # pfSense Hardening: Anti-DoS / SYN Flood rate limiting on WAN (%s)\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" tcp flags syn ct state new limit rate 100/second accept\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" tcp flags syn ct state new drop\n\n", cfg.WAN.Interface))

		buf.WriteString(fmt.Sprintf("    # pfSense Hardening: ICMP Ping Flood Protection on WAN (%s)\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" icmp type echo-request limit rate 10/second accept\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" icmp type echo-request drop\n\n", cfg.WAN.Interface))
	}

	buf.WriteString("    # Reject WAN unsolicited input\n")
	buf.WriteString("    drop\n")
	buf.WriteString("  }\n\n")

	// Forward Chain
	buf.WriteString("  chain forward {\n")
	buf.WriteString("    type filter hook forward priority filter; policy drop;\n\n")
	buf.WriteString("    # Allow established/related\n")
	buf.WriteString("    ct state established,related accept\n")
	buf.WriteString("    ct state invalid drop\n\n")

	buf.WriteString("    # pfSense Hardening: TCP MSS Clamping (MSS set to PMTU to prevent PPPoE fragmentation issues)\n")
	buf.WriteString("    tcp flags syn tcp option maxseg size set rt mtu\n\n")

	// Block direct WAN access for Restricted IP Alias (Forced through Squid Proxy)
	if cfg.SquidProxy.Enabled && len(cfg.SquidProxy.RestrictedIPs) > 0 {
		buf.WriteString("    # Block direct WAN traffic for Restricted IP Alias (Must use Squid Proxy)\n")
		for _, item := range cfg.SquidProxy.RestrictedIPs {
			ip := strings.TrimSpace(item.IPAddress)
			if ip != "" && item.Enabled {
				buf.WriteString(fmt.Sprintf("    ip saddr %s drop\n", ip))
			}
		}
		buf.WriteString("\n")
	}

	// LAN -> WAN Forwarding
	if cfg.LAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    # Allow LAN (%s) out to WAN\n", cfg.LAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" accept\n\n", cfg.LAN.Interface))
	}

	// Port Forwards (Forward Allow Rules)
	for _, pf := range cfg.Firewall.PortForwards {
		if !pf.Enabled {
			continue
		}
		proto := strings.ToLower(pf.Protocol)
		if proto == "both" {
			buf.WriteString(fmt.Sprintf("    # Port Forward: %s (TCP/UDP)\n", pf.Name))
			buf.WriteString(fmt.Sprintf("    ip daddr %s tcp dport %d accept\n", pf.InternalIP, pf.InternalPort))
			buf.WriteString(fmt.Sprintf("    ip daddr %s udp dport %d accept\n", pf.InternalIP, pf.InternalPort))
		} else {
			buf.WriteString(fmt.Sprintf("    # Port Forward: %s (%s)\n", pf.Name, strings.ToUpper(proto)))
			buf.WriteString(fmt.Sprintf("    ip daddr %s %s dport %d accept\n", pf.InternalIP, proto, pf.InternalPort))
		}
	}

	buf.WriteString("  }\n\n")

	// Output Chain
	buf.WriteString("  chain output {\n")
	buf.WriteString("    type filter hook output priority filter; policy accept;\n\n")
	if cfg.WAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    # pfSense Hardening: Block Bogon/Private source leakage on WAN output (%s)\n", cfg.WAN.Interface))
		buf.WriteString(fmt.Sprintf("    oifname \"%s\" ip saddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8, 0.0.0.0/8, 100.64.0.0/10, 224.0.0.0/4 } drop\n", cfg.WAN.Interface))
	}
	buf.WriteString("  }\n\n")

	// Prerouting (DNAT for Port Forwarding)
	buf.WriteString("  chain prerouting {\n")
	buf.WriteString("    type nat hook prerouting priority dstnat; policy accept;\n\n")
	for _, pf := range cfg.Firewall.PortForwards {
		if !pf.Enabled {
			continue
		}
		proto := strings.ToLower(pf.Protocol)
		if proto == "both" {
			buf.WriteString(fmt.Sprintf("    tcp dport %d dnat to %s:%d\n", pf.ExternalPort, pf.InternalIP, pf.InternalPort))
			buf.WriteString(fmt.Sprintf("    udp dport %d dnat to %s:%d\n", pf.ExternalPort, pf.InternalIP, pf.InternalPort))
		} else {
			buf.WriteString(fmt.Sprintf("    %s dport %d dnat to %s:%d\n", proto, pf.ExternalPort, pf.InternalIP, pf.InternalPort))
		}
	}
	buf.WriteString("  }\n\n")

	// Postrouting (Masquerade NAT)
	buf.WriteString("  chain postrouting {\n")
	buf.WriteString("    type nat hook postrouting priority srcnat; policy accept;\n\n")
	buf.WriteString("    # Masquerade outgoing LAN traffic on WAN interfaces (ppp0 / ethernet WAN)\n")
	buf.WriteString("    oifname \"ppp*\" masquerade\n")
	if cfg.WAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    oifname \"%s\" masquerade\n", cfg.WAN.Interface))
	}
	buf.WriteString("  }\n")

	buf.WriteString("}\n")

	return buf.String(), nil
}
