package services

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// GenerateNftables renders an atomic, deterministic nftables configuration string.
func GenerateNftables(cfg *config.SystemConfig) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString("# Table: inet minimalrouter\n\n")

	// Flush existing table to guarantee atomic replace
	buf.WriteString("table inet minimalrouter {\n")

	// Input Chain
	buf.WriteString("  chain input {\n")
	buf.WriteString("    type filter hook input priority filter; policy drop;\n\n")
	buf.WriteString("    # Allow loopback\n")
	buf.WriteString("    iifname \"lo\" accept\n\n")
	buf.WriteString("    # Allow established and related connections\n")
	buf.WriteString("    ct state established,related accept\n")
	buf.WriteString("    ct state invalid drop\n\n")

	// Allow Squid Proxy if enabled
	if cfg.SquidProxy.Enabled {
		port := cfg.SquidProxy.Port
		if port == 0 {
			port = 3128
		}
		buf.WriteString(fmt.Sprintf("    # Allow Squid Proxy (port %d)\n", port))
		buf.WriteString(fmt.Sprintf("    tcp dport %d accept\n\n", port))
	}

	// LAN Input permissions
	if cfg.LAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    # Allow all management and services from LAN (%s)\n", cfg.LAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" accept\n\n", cfg.LAN.Interface))
	}

	buf.WriteString("    # Reject WAN unsolicited input\n")
	buf.WriteString("    drop\n")
	buf.WriteString("  }\n\n")

	// Forward Chain
	buf.WriteString("  chain forward {\n")
	buf.WriteString("    type filter hook forward priority filter; policy drop;\n\n")
	buf.WriteString("    # Allow established/related\n")
	buf.WriteString("    ct state established,related accept\n")
	buf.WriteString("    ct state invalid drop\n\n")

	// Block direct WAN access for Restricted IP Alias (Forced through Squid Proxy)
	if cfg.SquidProxy.Enabled && len(cfg.SquidProxy.RestrictedIPs) > 0 {
		buf.WriteString("    # Block direct WAN traffic for Restricted IP Alias (Must use Squid Proxy)\n")
		for _, item := range cfg.SquidProxy.RestrictedIPs {
			ip := strings.TrimSpace(item.IPAddress)
			if ip != "" && item.Enabled {
				buf.WriteString(fmt.Sprintf("    ip saddr %s drop\n", ip))
			}
		}
		buf.WriteString("\n")
	}

	// LAN -> WAN Forwarding
	if cfg.LAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    # Allow LAN (%s) out to WAN\n", cfg.LAN.Interface))
		buf.WriteString(fmt.Sprintf("    iifname \"%s\" accept\n\n", cfg.LAN.Interface))
	}

	// Port Forwards (Forward Allow Rules)
	for _, pf := range cfg.Firewall.PortForwards {
		if !pf.Enabled {
			continue
		}
		proto := strings.ToLower(pf.Protocol)
		if proto == "both" {
			buf.WriteString(fmt.Sprintf("    # Port Forward: %s (TCP/UDP)\n", pf.Name))
			buf.WriteString(fmt.Sprintf("    ip daddr %s tcp dport %d accept\n", pf.InternalIP, pf.InternalPort))
			buf.WriteString(fmt.Sprintf("    ip daddr %s udp dport %d accept\n", pf.InternalIP, pf.InternalPort))
		} else {
			buf.WriteString(fmt.Sprintf("    # Port Forward: %s (%s)\n", pf.Name, strings.ToUpper(proto)))
			buf.WriteString(fmt.Sprintf("    ip daddr %s %s dport %d accept\n", pf.InternalIP, proto, pf.InternalPort))
		}
	}

	buf.WriteString("  }\n\n")

	// Output Chain
	buf.WriteString("  chain output {\n")
	buf.WriteString("    type filter hook output priority filter; policy accept;\n")
	buf.WriteString("  }\n\n")

	// Prerouting (DNAT for Port Forwarding)
	buf.WriteString("  chain prerouting {\n")
	buf.WriteString("    type nat hook prerouting priority dstnat; policy accept;\n\n")
	for _, pf := range cfg.Firewall.PortForwards {
		if !pf.Enabled {
			continue
		}
		proto := strings.ToLower(pf.Protocol)
		if proto == "both" {
			buf.WriteString(fmt.Sprintf("    tcp dport %d dnat to %s:%d\n", pf.ExternalPort, pf.InternalIP, pf.InternalPort))
			buf.WriteString(fmt.Sprintf("    udp dport %d dnat to %s:%d\n", pf.ExternalPort, pf.InternalIP, pf.InternalPort))
		} else {
			buf.WriteString(fmt.Sprintf("    %s dport %d dnat to %s:%d\n", proto, pf.ExternalPort, pf.InternalIP, pf.InternalPort))
		}
	}
	buf.WriteString("  }\n\n")

	// Postrouting (Masquerade NAT)
	buf.WriteString("  chain postrouting {\n")
	buf.WriteString("    type nat hook postrouting priority srcnat; policy accept;\n\n")
	buf.WriteString("    # Masquerade outgoing LAN traffic on WAN interfaces (ppp0 / ethernet WAN)\n")
	buf.WriteString("    oifname \"ppp*\" masquerade\n")
	if cfg.WAN.Interface != "" {
		buf.WriteString(fmt.Sprintf("    oifname \"%s\" masquerade\n", cfg.WAN.Interface))
	}
	buf.WriteString("  }\n")

	buf.WriteString("}\n")

	return buf.String(), nil
}
