package services

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

func quotePPPD(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	return strings.ReplaceAll(value, `"`, `\"`)
}

// PPPoEConfigBundle contains rendered peer config and secret material.
type PPPoEConfigBundle struct {
	PeerConfig  string
	ChapSecrets string
}

// GeneratePPPoE renders pppd configuration files.
func GeneratePPPoE(cfg *config.SystemConfig) (PPPoEConfigBundle, error) {
	var peerBuf bytes.Buffer

	peerBuf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	peerBuf.WriteString(fmt.Sprintf("plugin pppoe.so %s\n", cfg.WAN.Interface))
	peerBuf.WriteString(fmt.Sprintf("name \"%s\"\n", quotePPPD(cfg.WAN.Username)))
	peerBuf.WriteString("noipdefault\n")
	peerBuf.WriteString("noauth\n")
	peerBuf.WriteString("noipv6\n")
	peerBuf.WriteString("defaultroute\n")
	peerBuf.WriteString("replacedefaultroute\n")

	if cfg.WAN.UsePeerDNS {
		peerBuf.WriteString("usepeerdns\n")
	}

	peerBuf.WriteString("persist\n")
	peerBuf.WriteString("maxfail 0\n")
	peerBuf.WriteString("holdoff 5\n")

	if cfg.WAN.MTU > 0 {
		peerBuf.WriteString(fmt.Sprintf("mtu %d\n", cfg.WAN.MTU))
		peerBuf.WriteString(fmt.Sprintf("mru %d\n", cfg.WAN.MTU))
	}

	var secretBuf bytes.Buffer
	secretBuf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	secretBuf.WriteString(fmt.Sprintf("\"%s\" * \"%s\" *\n", quotePPPD(cfg.WAN.Username), quotePPPD(cfg.WAN.Password)))

	return PPPoEConfigBundle{
		PeerConfig:  peerBuf.String(),
		ChapSecrets: secretBuf.String(),
	}, nil
}
