package services

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// QoSCommands returns argv-only tc operations for CAKE or fq_codel. The
// privileged helper executes these directly; no generated text reaches a
// shell.
func QoSCommands(cfg *config.SystemConfig) ([][]string, error) {
	if !cfg.QoS.Enabled {
		return nil, nil
	}

	iface := qosInterface(cfg)
	downKbit := strconv.Itoa(cfg.QoS.DownloadLimitMbps * 1000)
	upKbit := strconv.Itoa(cfg.QoS.UploadLimitMbps * 1000)

	switch cfg.QoS.Algorithm {
	case "fq_codel":
		return [][]string{
			{"qdisc", "add", "dev", iface, "root", "handle", "1:", "htb", "default", "10"},
			{"class", "add", "dev", iface, "parent", "1:", "classid", "1:10", "htb", "rate", upKbit + "kbit", "ceil", upKbit + "kbit", "burst", "64k"},
			{"qdisc", "add", "dev", iface, "parent", "1:10", "handle", "10:", "fq_codel", "target", "5ms", "interval", "100ms", "limit", "10240"},
			{"qdisc", "add", "dev", iface, "handle", "ffff:", "ingress"},
			{"filter", "add", "dev", iface, "parent", "ffff:", "protocol", "ip", "u32", "match", "u32", "0", "0", "police", "rate", downKbit + "kbit", "burst", "64k", "drop", "flowid", ":1"},
		}, nil
	case "cake":
		return [][]string{
			{"qdisc", "add", "dev", iface, "root", "cake", "bandwidth", upKbit + "kbit", "besteffort", "nat", "wash", "no-split-gso"},
			{"qdisc", "add", "dev", iface, "handle", "ffff:", "ingress"},
			{"filter", "add", "dev", iface, "parent", "ffff:", "protocol", "ip", "u32", "match", "u32", "0", "0", "police", "rate", downKbit + "kbit", "burst", "64k", "drop", "flowid", ":1"},
		}, nil
	default:
		return nil, fmt.Errorf("unsupported QoS algorithm: %s", cfg.QoS.Algorithm)
	}
}

func qosInterface(cfg *config.SystemConfig) string {
	iface := cfg.WAN.Interface
	if cfg.WAN.Enabled {
		iface = "ppp0"
	}
	if iface == "" {
		iface = "eth0"
	}
	return iface
}

// GenerateQoS produces a human-readable record of the exact tc operations.
// It is installed as a non-executable plan for diagnostics and rollback
// review; QoSCommands is the executable source of truth.
func GenerateQoS(cfg *config.SystemConfig) (string, error) {
	if !cfg.QoS.Enabled {
		return "# QoS disabled\n", nil
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — non-executable QoS plan\n")
	buf.WriteString("# router-applyd invokes /sbin/tc directly with these argv values\n\n")
	commands, err := QoSCommands(cfg)
	if err != nil {
		return "", err
	}
	for _, args := range commands {
		buf.WriteString("/sbin/tc ")
		buf.WriteString(strings.Join(args, " "))
		buf.WriteByte('\n')
	}

	return buf.String(), nil
}
