package services

import (
	"bytes"
	"fmt"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// GenerateQoS produces tc (traffic control) commands for CAKE or fq_codel
// traffic shaping. The output is a shell script that configures the qdiscs
// on the WAN interface to prevent bufferbloat.
func GenerateQoS(cfg *config.SystemConfig) (string, error) {
	if !cfg.QoS.Enabled {
		return "# QoS disabled\n", nil
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by Minimal Router OS — QoS traffic shaping\n")
	buf.WriteString("# Uses tc (traffic control) with CAKE or fq_codel qdisc\n\n")

	iface := cfg.WAN.Interface
	if iface == "" {
		iface = "eth0"
	}

	downMbps := cfg.QoS.DownloadLimitMbps
	upMbps := cfg.QoS.UploadLimitMbps

	// Convert Mbps to kbit for tc
	downKbit := downMbps * 1000
	upKbit := upMbps * 1000

	buf.WriteString("# Clean existing qdiscs\n")
	buf.WriteString(fmt.Sprintf("tc qdisc del dev %s root 2>/dev/null || true\n", iface))
	buf.WriteString(fmt.Sprintf("tc qdisc del dev %s ingress 2>/dev/null || true\n\n", iface))

	switch cfg.QoS.Algorithm {
	case "fq_codel":
		buf.WriteString("# ── fq_codel qdisc (ingress shaping) ──\n")
		buf.WriteString(fmt.Sprintf("tc qdisc add dev %s root fq_codel target 5ms interval 100ms limit 10240 flows 1024 quantum 1514\n", iface))
		buf.WriteString(fmt.Sprintf("\n# Download limit: %d Mbps\n", downMbps))
		buf.WriteString(fmt.Sprintf("tc qdisc add dev %s handle ffff: ingress\n", iface))
		buf.WriteString(fmt.Sprintf("tc filter add dev %s parent ffff: protocol ip u32 match u32 0 0 police rate %dkbit burst 64k drop flowid :1\n\n", iface, downKbit))

		buf.WriteString("# Upload limit\n")
		buf.WriteString(fmt.Sprintf("tc qdisc add dev %s root handle 1: htb default 10\n", iface))
		buf.WriteString(fmt.Sprintf("tc class add dev %s parent 1: classid 1:10 htb rate %dkbit ceil %dkbit burst 64k\n", iface, upKbit, upKbit))
		buf.WriteString(fmt.Sprintf("tc qdisc add dev %s parent 1:10 fq_codel target 5ms interval 100ms limit 10240\n\n", iface))

	case "cake":
		buf.WriteString("# ── CAKE qdisc (Advanced bufferbloat prevention) ──\n")
		buf.WriteString(fmt.Sprintf("# Download shaping: %d Mbps\n", downMbps))
		buf.WriteString(fmt.Sprintf("tc qdisc add dev %s handle ffff: ingress\n", iface))
		buf.WriteString(fmt.Sprintf("tc filter add dev %s parent ffff: protocol ip u32 match u32 0 0 police rate %dkbit burst 64k drop flowid :1\n", iface, downKbit))
		buf.WriteString(fmt.Sprintf("tc qdisc add dev %s ffff: cake bandwidth %dkbit besteffort nat wash no-split-gso\n\n", iface, downKbit))

		buf.WriteString("# Upload shaping\n")
		buf.WriteString(fmt.Sprintf("tc qdisc add dev %s root handle 1: htb default 10\n", iface))
		buf.WriteString(fmt.Sprintf("tc class add dev %s parent 1: classid 1:10 htb rate %dkbit ceil %dkbit burst 64k\n", iface, upKbit, upKbit))
		buf.WriteString(fmt.Sprintf("tc qdisc add dev %s parent 1:10 cake bandwidth %dkbit besteffort nat wash no-split-gso\n\n", iface, upKbit))

	default:
		return "", fmt.Errorf("unsupported QoS algorithm: %s", cfg.QoS.Algorithm)
	}

	buf.WriteString("# Verify qdiscs are active\n")
	buf.WriteString(fmt.Sprintf("tc qdisc show dev %s\n", iface))

	return buf.String(), nil
}
