package services

import (
	"bytes"
	"fmt"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// GenerateSquidConfig renders a non-caching, authenticated forward proxy configuration for Alpine Linux.
func GenerateSquidConfig(cfg *config.SystemConfig) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString(fmt.Sprintf("http_port %d\n\n", cfg.SquidProxy.Port))

	buf.WriteString("# Disable disk & memory caching (Pure forward proxy)\n")
	buf.WriteString("cache deny all\n")
	buf.WriteString("cache_mem 0 MB\n\n")

	if cfg.SquidProxy.Username != "" {
		buf.WriteString("# Basic authentication scheme (NCSA htpasswd)\n")
		buf.WriteString("auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd\n")
		buf.WriteString("auth_param basic realm Minimal Router OS Proxy\n")
		buf.WriteString("acl authenticated proxy_auth REQUIRED\n")
		buf.WriteString("http_access allow authenticated\n")
	} else {
		buf.WriteString("acl localnet src 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16\n")
		buf.WriteString("http_access allow localnet\n")
	}

	buf.WriteString("http_access deny all\n")

	return buf.String(), nil
}
