package services

import (
	"bytes"
	"fmt"
	"net"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

// GenerateSquidConfig renders a non-caching, authenticated forward proxy configuration for Alpine Linux.
func GenerateSquidConfig(cfg *config.SystemConfig) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString(fmt.Sprintf("http_port %s:%d\n\n", cfg.LAN.IPAddress, cfg.SquidProxy.Port))

	buf.WriteString("# Disable disk & memory caching (Pure forward proxy)\n")
	buf.WriteString("cache deny all\n")
	buf.WriteString("cache_mem 0 MB\n")
	buf.WriteString("# Short graceful shutdown so config rollback never waits on idle clients\n")
	buf.WriteString("shutdown_lifetime 2 seconds\n\n")

	if cfg.SquidProxy.Enabled {
		buf.WriteString("# Basic authentication scheme (NCSA htpasswd)\n")
		buf.WriteString("auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd\n")
		buf.WriteString("auth_param basic realm Minimal Router OS Proxy\n")
		buf.WriteString("auth_param basic credentialsttl 2 hours\n")
		_, lanNetwork, _ := net.ParseCIDR(cfg.LAN.CIDR)
		buf.WriteString(fmt.Sprintf("acl localnet src %s\n", lanNetwork.String()))
		buf.WriteString("acl authenticated proxy_auth REQUIRED\n")
		buf.WriteString("http_access allow localnet authenticated\n")
	} else {
		buf.WriteString("# Proxy disabled\n")
	}

	buf.WriteString("http_access deny all\n")

	return buf.String(), nil
}
