package services

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/vladimirperovic/minimalrouter/internal/config"
)

type WireGuardConfig = config.WireGuardConfig
type WireGuardPeer = config.WireGuardPeer

// GenerateWireGuard renders the human-readable appliance configuration. It
// includes Address, which is applied by the privileged helper with a fixed
// ip(8) argv and is not valid input for wg setconf.
func GenerateWireGuard(wg *WireGuardConfig) (string, error) {
	return generateWireGuard(wg, true)
}

// GenerateWireGuardRuntime renders only directives accepted by wg setconf.
// Keeping the runtime file separate removes the need for wg-quick (and Bash)
// without parsing or executing shell hooks from configuration.
func GenerateWireGuardRuntime(wg *WireGuardConfig) (string, error) {
	return generateWireGuard(wg, false)
}

func generateWireGuard(wg *WireGuardConfig, includeAddress bool) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	if includeAddress {
		buf.WriteString("# Runtime file: /run/minimalrouter/wg0.conf\n\n")
	} else {
		buf.WriteString("# Runtime input for wg setconf; interface address is applied separately\n\n")
	}

	buf.WriteString("[Interface]\n")
	buf.WriteString(fmt.Sprintf("PrivateKey = %s\n", wg.PrivateKey))
	if wg.ListenPort > 0 {
		buf.WriteString(fmt.Sprintf("ListenPort = %d\n", wg.ListenPort))
	} else {
		buf.WriteString("ListenPort = 51820\n")
	}
	if includeAddress {
		buf.WriteString(fmt.Sprintf("Address = %s\n", wg.Address))
	}
	buf.WriteString("\n")

	for _, peer := range wg.Peers {
		if !peer.Enabled {
			continue
		}
		buf.WriteString("# Peer: " + peer.Name + "\n")
		buf.WriteString("[Peer]\n")
		buf.WriteString(fmt.Sprintf("PublicKey = %s\n", peer.PublicKey))

		if peer.PresharedKey != "" {
			buf.WriteString(fmt.Sprintf("PresharedKey = %s\n", peer.PresharedKey))
		}

		if len(peer.AllowedIPs) > 0 {
			buf.WriteString(fmt.Sprintf("AllowedIPs = %s\n", strings.Join(peer.AllowedIPs, ", ")))
		}

		if peer.Endpoint != "" {
			buf.WriteString(fmt.Sprintf("Endpoint = %s\n", peer.Endpoint))
		}
		buf.WriteString("PersistentKeepalive = 25\n\n")
	}

	return buf.String(), nil
}
