package services

import (
	"bytes"
	"fmt"
	"strings"
)

// WireGuardConfig represents the internal domain model for WireGuard VPN settings.
type WireGuardConfig struct {
	Enabled    bool            `json:"enabled"`
	Interface  string          `json:"interface"`   // e.g. "wg0"
	PrivateKey string          `json:"private_key"` // Redacted in status
	ListenPort int             `json:"listen_port"` // Default 51820
	Address    string          `json:"address"`     // e.g. "10.0.0.1/24"
	Peers      []WireGuardPeer `json:"peers"`
}

// WireGuardPeer represents a client/remote peer configuration.
type WireGuardPeer struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	PublicKey    string   `json:"public_key"`
	PresharedKey string   `json:"preshared_key,omitempty"`
	AllowedIPs   []string `json:"allowed_ips"` // e.g. ["10.0.0.2/32"]
	Endpoint     string   `json:"endpoint,omitempty"`
	Enabled      bool     `json:"enabled"`
}

// GenerateWireGuard renders the /etc/wireguard/wg0.conf configuration file.
func GenerateWireGuard(wg *WireGuardConfig) (string, error) {
	var buf bytes.Buffer

	buf.WriteString("# Generated by Minimal Router OS — do not edit manually\n")
	buf.WriteString("# File: /etc/wireguard/wg0.conf\n\n")

	buf.WriteString("[Interface]\n")
	buf.WriteString(fmt.Sprintf("PrivateKey = %s\n", wg.PrivateKey))
	if wg.ListenPort > 0 {
		buf.WriteString(fmt.Sprintf("ListenPort = %d\n", wg.ListenPort))
	} else {
		buf.WriteString("ListenPort = 51820\n")
	}
	buf.WriteString(fmt.Sprintf("Address = %s\n\n", wg.Address))

	for _, peer := range wg.Peers {
		if !peer.Enabled {
			continue
		}
		buf.WriteString("# Peer: " + peer.Name + "\n")
		buf.WriteString("[Peer]\n")
		buf.WriteString(fmt.Sprintf("PublicKey = %s\n", peer.PublicKey))

		if peer.PresharedKey != "" {
			buf.WriteString(fmt.Sprintf("PresharedKey = %s\n", peer.PresharedKey))
		}

		if len(peer.AllowedIPs) > 0 {
			buf.WriteString(fmt.Sprintf("AllowedIPs = %s\n", strings.Join(peer.AllowedIPs, ", ")))
		}

		if peer.Endpoint != "" {
			buf.WriteString(fmt.Sprintf("Endpoint = %s\n", peer.Endpoint))
		}
		buf.WriteString("PersistentKeepalive = 25\n\n")
	}

	return buf.String(), nil
}
